[package]
name = "plugin-host"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libloading = "0.9.0"
telekio-abi = { version = "0.1.0", path = "../../crates/telekio-abi" }
telekio-host = { version = "0.1.0", path = "../../crates/telekio-host" }
tokio = { version = "1.53.1", features = ["full"] }
