[workspace]
members = ["features", "host", "plugin", "support", "support-host", "upstream"]
default-members = ["upstream"]
resolver = "3"

[patch.crates-io]
telekio-abi = { path = "../crates/telekio-abi" }
telekio-build = { path = "../crates/telekio-build" }
telekio-host = { path = "../crates/telekio-host" }
