use std::{
    error::Error,
    ffi::{OsStr, OsString},
    fs,
    path::Path,
};

use telekio_build::{Role, prepare_patch};
use toml_edit::{DocumentMut, Item};

use super::cargo;

const DIRECTORY: &str = ".telekio/tokio";
const PATCH_PATH: &str = ".telekio/tokio";
const GENERATED: &str = "Generated by Telekio.";

pub(super) struct ProjectInfo {
    host: Vec<String>,
    guest: Vec<String>,
    pub(super) workspace_selection: bool,
    pub(super) workspace_mixed: bool,
}

impl ProjectInfo {
    pub(super) fn role(&self) -> Option<Role> {
        match (self.host.is_empty(), self.guest.is_empty()) {
            (false, true) => Some(Role::Host),
            (true, false) => Some(Role::Guest),
            _ => None,
        }
    }

    pub(super) fn package_names(&self) -> Vec<String> {
        self.host.iter().chain(&self.guest).cloned().collect()
    }

    pub(super) fn groups(&self) -> (&[String], &[String]) {
        (&self.host, &self.guest)
    }
}

pub(super) fn uses_tokio(metadata: &serde_json::Value) -> bool {
    metadata["packages"]
        .as_array()
        .into_iter()
        .flatten()
        .any(|package| {
            (package["name"].as_str() == Some("tokio")
                && (crates_io(package) || generated_patch(package)))
                || package["dependencies"]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .any(|dependency| {
                        dependency["name"].as_str() == Some("tokio") && crates_io(dependency)
                    })
        })
}

pub(super) fn info(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
    metadata: &serde_json::Value,
) -> Result<ProjectInfo, Box<dyn Error>> {
    let packages = metadata["packages"]
        .as_array()
        .ok_or("Cargo metadata has no packages")?;
    let (selected, workspace_selection) =
        selected_packages(cargo, arguments, manifest, metadata, packages)?;
    let mut host = Vec::new();
    let mut guest = Vec::new();
    for id in selected {
        let package = packages
            .iter()
            .find(|package| package["id"].as_str() == Some(id))
            .ok_or("selected Cargo package was not found")?;
        let name = package["name"]
            .as_str()
            .ok_or("selected Cargo package has no name")?
            .to_owned();
        match package_role(package) {
            Role::Host => host.push(name),
            Role::Guest => guest.push(name),
        }
    }
    let workspace_roles = metadata["workspace_members"]
        .as_array()
        .ok_or("Cargo metadata has no workspace members")?
        .iter()
        .filter_map(serde_json::Value::as_str)
        .filter_map(|id| {
            packages
                .iter()
                .find(|package| package["id"].as_str() == Some(id))
        })
        .map(package_role)
        .collect::<Vec<_>>();
    Ok(ProjectInfo {
        host,
        guest,
        workspace_selection,
        workspace_mixed: workspace_roles.contains(&Role::Host)
            && workspace_roles.contains(&Role::Guest),
    })
}

fn package_role(package: &serde_json::Value) -> Role {
    let mut guest = false;
    for dependency in package["dependencies"]
        .as_array()
        .into_iter()
        .flatten()
        .filter(|dependency| dependency["kind"].is_null())
    {
        let name = dependency["name"].as_str();
        let rename = dependency["rename"].as_str();
        if name == Some("telekio-host") || matches!(rename, Some("telekio-host" | "telekio_host")) {
            return Role::Host;
        }
        if name == Some("telekio-abi") {
            guest = true;
        }
    }
    if guest { Role::Guest } else { Role::Host }
}

pub(super) fn verify_patch(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
    config: &Path,
    selected: &[String],
) -> Result<(), Box<dyn Error>> {
    let metadata = cargo::metadata(cargo, arguments, manifest, Some(config), false)?;
    if cargo::operation(arguments) == Some("update") {
        return Ok(());
    }
    let packages = metadata["packages"]
        .as_array()
        .ok_or("Cargo metadata has no packages")?;
    let members = metadata["workspace_members"]
        .as_array()
        .ok_or("Cargo metadata has no workspace members")?;
    let ids = packages
        .iter()
        .filter(|package| {
            package["id"]
                .as_str()
                .is_some_and(|id| members.iter().any(|member| member.as_str() == Some(id)))
                && package["name"]
                    .as_str()
                    .is_some_and(|name| selected.iter().any(|selected| selected == name))
        })
        .filter_map(|package| package["id"].as_str())
        .collect::<Vec<_>>();
    let reachable = reachable_packages(&metadata, &ids)?;
    let expected = fs::canonicalize(
        config
            .parent()
            .ok_or("Telekio config has no parent")?
            .join("tokio/Cargo.toml"),
    )?;
    for package in packages
        .iter()
        .filter(|package| package["name"].as_str() == Some("tokio"))
    {
        let path = package["manifest_path"]
            .as_str()
            .and_then(|path| fs::canonicalize(path).ok());
        if path.as_ref() != Some(&expected)
            && package["id"]
                .as_str()
                .is_some_and(|id| reachable.contains(&id))
            && (crates_io(package) || generated_patch(package))
        {
            return Err("generated Tokio patch was not selected; run `telekio cargo update -p tokio`, or `cargo update -p tokio` after `telekio init`, then adjust incompatible Tokio version requirements".into());
        }
    }
    Ok(())
}

fn selected_packages<'a>(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
    metadata: &'a serde_json::Value,
    packages: &'a [serde_json::Value],
) -> Result<(Vec<&'a str>, bool), Box<dyn Error>> {
    let operation = cargo::operation(arguments);
    let workspace =
        cargo::has_option(arguments, "--workspace") || cargo::has_option(arguments, "--all");
    let requested = cargo::option_values(arguments, &["-p", "--package"]);
    let workspace_members = metadata["workspace_members"]
        .as_array()
        .ok_or("Cargo metadata has no workspace members")?;
    let members = if workspace {
        workspace_members
    } else {
        metadata["workspace_default_members"]
            .as_array()
            .ok_or("Cargo metadata has no default workspace members")?
    };
    let mut selected = members
        .iter()
        .filter_map(serde_json::Value::as_str)
        .collect::<Vec<_>>();
    let mut selects_workspace = operation.is_some_and(cargo::package_selects_workspace);
    if selects_workspace && (!requested.is_empty() || cargo::has_option(arguments, "--exclude")) {
        let names = cargo::selected_packages(cargo, arguments, manifest)?;
        let ids = packages
            .iter()
            .filter(|package| {
                workspace_members.contains(&package["id"])
                    && package["name"]
                        .as_str()
                        .is_some_and(|name| names.iter().any(|selected| selected == name))
            })
            .filter_map(|package| package["id"].as_str())
            .collect::<Vec<_>>();
        selects_workspace = ids.len() == names.len();
        if selects_workspace {
            selected = ids;
        }
    }
    if selected.is_empty() {
        return Err("Cargo package selection matched no packages".into());
    }
    Ok((selected, selects_workspace))
}

fn crates_io(package: &serde_json::Value) -> bool {
    package["source"]
        .as_str()
        .is_some_and(|source| source.contains("crates.io-index"))
}

fn generated_patch(package: &serde_json::Value) -> bool {
    package["manifest_path"]
        .as_str()
        .and_then(|manifest| fs::read_to_string(manifest).ok())
        .is_some_and(|manifest| manifest.lines().any(|line| line.contains(GENERATED)))
}

fn reachable_packages<'a>(
    metadata: &'a serde_json::Value,
    selected: &[&'a str],
) -> Result<Vec<&'a str>, Box<dyn Error>> {
    let nodes = metadata["resolve"]["nodes"]
        .as_array()
        .ok_or("Cargo metadata has no resolve nodes")?;
    let mut reachable = selected.to_vec();
    let mut index = 0;
    while index < reachable.len() {
        if let Some(node) = nodes
            .iter()
            .find(|node| node["id"].as_str() == Some(reachable[index]))
            && let Some(dependencies) = node["dependencies"].as_array()
        {
            for dependency in dependencies.iter().filter_map(serde_json::Value::as_str) {
                if !reachable.contains(&dependency) {
                    reachable.push(dependency);
                }
            }
        }
        index += 1;
    }
    Ok(reachable)
}

pub(super) fn init(manifest: &Path, role: Role, offline: bool) -> Result<(), Box<dyn Error>> {
    let root = manifest.parent().ok_or("manifest has no parent")?;
    let mut document = fs::read_to_string(manifest)?.parse::<DocumentMut>()?;
    if let Some(patch) = tokio_patch(&document)
        && patch.get("path").and_then(Item::as_str) != Some(PATCH_PATH)
    {
        return Err(format!("Tokio already has a patch in {}", manifest.display()).into());
    }
    let directory = root.join(DIRECTORY);
    validate_destination(&directory)?;
    prepare_patch(&directory, role, offline)?;
    set_patch(&mut document)?;
    fs::write(manifest, document.to_string())?;
    Ok(())
}

pub(super) fn remove(manifest: &Path) -> Result<(), Box<dyn Error>> {
    let root = manifest.parent().ok_or("manifest has no parent")?;
    let mut document = fs::read_to_string(manifest)?.parse::<DocumentMut>()?;
    if patch_path(&document).as_deref() != Some(PATCH_PATH) {
        return Err("this package does not use its Telekio patch".into());
    }
    let directory = root.join(DIRECTORY);
    validate_patch(&directory)?;
    validate_parent(directory.parent().ok_or("patch has no parent")?)?;
    remove_patch(&mut document)?;

    fs::write(manifest, document.to_string())?;
    fs::remove_dir_all(directory.parent().ok_or("patch has no parent")?)?;
    Ok(())
}

fn tokio_patch(manifest: &DocumentMut) -> Option<&Item> {
    manifest.get("patch")?.get("crates-io")?.get("tokio")
}

fn patch_path(manifest: &DocumentMut) -> Option<String> {
    tokio_patch(manifest)?
        .get("path")?
        .as_str()
        .map(str::to_owned)
}

fn set_patch(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let patch: DocumentMut =
        format!("[patch.crates-io]\ntokio = {{ path = {PATCH_PATH:?} }}\n").parse()?;
    if manifest.get("patch").is_none() {
        let mut table = toml_edit::Table::new();
        table.set_implicit(true);
        manifest.insert("patch", Item::Table(table));
    }
    let patches = manifest["patch"]
        .as_table_mut()
        .ok_or("patch is not a table")?;
    if patches.get("crates-io").is_none() {
        patches.insert("crates-io", Item::Table(Default::default()));
    }
    patches["crates-io"]
        .as_table_mut()
        .ok_or("patch.crates-io is not a table")?
        .insert("tokio", patch["patch"]["crates-io"]["tokio"].clone());
    Ok(())
}

fn remove_patch(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let patches = manifest["patch"]
        .as_table_mut()
        .ok_or("patch is not a table")?;
    let crates_io = patches["crates-io"]
        .as_table_mut()
        .ok_or("patch.crates-io is not a table")?;
    crates_io.remove("tokio");
    if crates_io.is_empty() {
        patches.remove("crates-io");
    }
    if patches.is_empty() {
        manifest.remove("patch");
    }
    Ok(())
}

fn validate_destination(directory: &Path) -> Result<(), Box<dyn Error>> {
    let parent = directory.parent().ok_or("patch has no parent")?;
    if parent.exists() {
        validate_parent(parent)?;
    }
    if directory.exists() {
        validate_patch(directory)?;
    }
    Ok(())
}

fn validate_parent(directory: &Path) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        if entry.file_name() != "tokio" {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    Ok(())
}

fn validate_patch(directory: &Path) -> Result<(), Box<dyn Error>> {
    for path in [
        directory.join("Cargo.toml"),
        directory.join("build.rs"),
        directory.join("src/lib.rs"),
    ] {
        let source = fs::read_to_string(&path).map_err(|error| {
            format!("could not read generated file {}: {error}", path.display())
        })?;
        if !source.lines().any(|line| line.contains(GENERATED)) {
            return Err(format!("{} is not generated by Telekio", path.display()).into());
        }
    }
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        if entry.file_name() != "Cargo.toml"
            && entry.file_name() != "build.rs"
            && entry.file_name() != "src"
        {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    for entry in fs::read_dir(directory.join("src"))? {
        let entry = entry?;
        if entry.file_name() != "lib.rs" {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    Ok(())
}
