[package]
name = "telekio-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Cargo wrapper for Telekio"

[[bin]]
name = "telekio"
path = "src/main.rs"
doc = false

[package.metadata.binstall]
pkg-url = "{repo}/releases/download/v{version}/telekio-{target}{archive-suffix}"
bin-dir = "{bin}{binary-ext}"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.'cfg(windows)']
pkg-fmt = "zip"

[dependencies]
serde_json = "1"
telekio-build = { version = "=0.1.0", path = "../telekio-build" }
toml_edit = "0.25.13"
