use std::{
    env,
    error::Error,
    ffi::{OsStr, OsString},
    fs,
    path::{Path, PathBuf},
    process::{self, Command},
};

use ra_ap_syntax::{
    AstNode, Edition, SourceFile,
    ast::{self, HasName},
};
use serde_json::Value as Json;
use sysinfo::{Pid, System};
use toml_edit::{ArrayOfTables, DocumentMut, Item, Table, value};

use crate::{edit, guest::prepare_artifact_guest, linker, source::include_source};

const DIRECTORY: &str = ".telekio";
const GENERATED: &str = "// Generated by Telekio.";
const TARGET_COMMENT: &str = "# Generated by Telekio. Artifact proxy.";
const INNER_CFG: &str = "cfg(telekio_inner)";
const INNER_COMMENT: &str = "# Generated by Telekio. Compiled in the inner artifact.";
const TARGET_DEP_COMMENT: &str = "# Generated by Telekio. Compiled in the inner target.";

#[derive(Clone, Copy)]
pub enum Artifact {
    Host,
    Plugin,
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum Kind {
    Lib,
    Bin,
    Test,
    Example,
    Bench,
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum Origin {
    Inferred,
    Declared,
    Explicit,
}

struct Target {
    name: String,
    kind: Kind,
    source: PathBuf,
    test: bool,
}

pub fn init(artifact: Artifact) -> bool {
    match init_result(artifact) {
        Ok(result) => result,
        Err(error) => panic!("Telekio build failed: {error}"),
    }
}

pub fn remove() -> bool {
    match remove_result() {
        Ok(result) => result,
        Err(error) => panic!("Telekio removal failed: {error}"),
    }
}

fn init_result(artifact: Artifact) -> Result<bool, Box<dyn Error>> {
    let root = package_root()?;
    if inner_build() {
        let targets = targets(&root)?;
        write_inner_sources(
            &PathBuf::from(env::var_os("OUT_DIR").ok_or("OUT_DIR is unavailable")?).join("telekio"),
            &targets,
            artifact,
        )?;
        return Ok(false);
    }
    let targets = targets(&root)?;
    let pending = targets
        .iter()
        .filter(|target| !generated(&target.source))
        .collect::<Vec<_>>();
    if pending.is_empty() && isolated(&root)? {
        build(artifact, &root, &targets)?;
    } else {
        initialize(&root, &pending, artifact)?;
        println!("cargo::error=Telekio updated this package; run Cargo again");
    }
    Ok(true)
}

fn remove_result() -> Result<bool, Box<dyn Error>> {
    if inner_build() {
        return Ok(false);
    }
    let root = package_root()?;
    let targets = targets(&root)?;
    if !targets.iter().all(|target| generated(&target.source)) {
        return Err("this package is not fully initialized by Telekio".into());
    }

    let manifest_path = root.join("Cargo.toml");
    let mut manifest = fs::read_to_string(&manifest_path)?.parse::<DocumentMut>()?;
    for target in &targets {
        restore_target(&mut manifest, &root, target)?;
    }
    restore_dependencies(&mut manifest)?;
    remove_package_include(&mut manifest);
    remove_build_dependency(&mut manifest)?;
    fs::write(&manifest_path, manifest.to_string())?;

    let build = build_script(&manifest, &root)?;
    let source = fs::read_to_string(&build)?;
    fs::write(&build, remove_action(&source)?)?;
    remove_generated(&root.join(DIRECTORY))?;
    println!("cargo::error=Telekio was removed from this package; run Cargo again");
    Ok(true)
}

fn inner_build() -> bool {
    env::var_os("OUT_DIR")
        .map(PathBuf::from)
        .is_some_and(|out| {
            out.ancestors()
                .any(|path| path.join(".telekio-inner").is_file())
        })
}

fn initialize(root: &Path, targets: &[&Target], artifact: Artifact) -> Result<(), Box<dyn Error>> {
    let directory = root.join(DIRECTORY);
    match fs::read_dir(&directory) {
        Ok(mut entries) => {
            for entry in &mut entries {
                let entry = entry?;
                if !entry.file_type()?.is_file()
                    || !fs::read_to_string(entry.path())?.starts_with(GENERATED)
                {
                    return Err(
                        format!("{} contains non-Telekio files", directory.display()).into(),
                    );
                }
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            fs::create_dir(&directory)?;
        }
        Err(error) => return Err(error.into()),
    }

    let manifest_path = root.join("Cargo.toml");
    let mut manifest = fs::read_to_string(&manifest_path)?.parse::<DocumentMut>()?;
    for target in targets {
        let origin = target_origin(&manifest, root, target)?;
        let proxy = proxy_path(root, target, origin);
        fs::write(&proxy, proxy_source(root, target, &proxy)?)?;
        set_target_path(&mut manifest, root, target, &proxy)?;
    }
    isolate_dependencies(&mut manifest, artifact)?;
    add_package_include(&mut manifest)?;
    fs::write(manifest_path, manifest.to_string())?;
    Ok(())
}

fn isolated(root: &Path) -> Result<bool, Box<dyn Error>> {
    let manifest: DocumentMut = fs::read_to_string(root.join("Cargo.toml"))?.parse()?;
    Ok(manifest
        .get("target")
        .and_then(Item::as_table)
        .and_then(|target| target.get(INNER_CFG))
        .is_some())
}

fn isolate_dependencies(
    manifest: &mut DocumentMut,
    artifact: Artifact,
) -> Result<(), Box<dyn Error>> {
    let has_inner = manifest
        .get("target")
        .and_then(Item::as_table)
        .and_then(|target| target.get(INNER_CFG))
        .is_some();
    if !has_inner {
        if manifest.get("target").is_none() {
            let mut target = Table::new();
            target.set_implicit(true);
            manifest.insert("target", Item::Table(target));
        }
        let target = manifest
            .get_mut("target")
            .and_then(Item::as_table_mut)
            .ok_or("target table is invalid")?;
        let mut inner = Table::new();
        inner.set_implicit(true);
        target.insert(INNER_CFG, Item::Table(inner));
    }

    isolate_target_dependencies(manifest)?;
    let dependencies = manifest.remove("dependencies");
    let dev_dependencies = manifest.remove("dev-dependencies");
    let inner = manifest
        .get_mut("target")
        .and_then(Item::as_table_mut)
        .and_then(|target| target.get_mut(INNER_CFG))
        .and_then(Item::as_table_mut)
        .ok_or("Telekio inner target is invalid")?;
    if let Some(item) = dependencies {
        inner.insert("dependencies", item);
    }
    if let Some(item) = dev_dependencies {
        inner.insert("dev-dependencies", item);
    }
    let dependencies = inner
        .entry("dependencies")
        .or_insert(Item::Table(Table::new()))
        .as_table_mut()
        .ok_or("inner dependencies is not a table")?;
    add_table_comment(dependencies, INNER_COMMENT);
    if !dependencies.contains_key("telekio") {
        dependencies.insert("telekio", dependency_item("telekio", true)?);
    }
    if matches!(artifact, Artifact::Host) && !dependencies.contains_key("telekio-host") {
        dependencies.insert("telekio-host", dependency_item("telekio-host", false)?);
    }
    Ok(())
}

fn isolate_target_dependencies(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let names = manifest
        .get("target")
        .and_then(Item::as_table)
        .map(|target| {
            target
                .iter()
                .filter(|(name, _)| *name != INNER_CFG && !is_inner_target_name(name))
                .map(|(name, _)| name.to_owned())
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    for name in names {
        let Some(mut item) = manifest
            .get_mut("target")
            .and_then(Item::as_table_mut)
            .and_then(|target| target.remove(&name))
        else {
            continue;
        };
        let table = item
            .as_table_mut()
            .ok_or("target dependency table is invalid")?;
        let mut inner = Table::new();
        for section in ["dependencies", "dev-dependencies"] {
            if let Some(item) = table.remove(section) {
                inner.insert(section, item);
            }
        }
        inner.set_implicit(true);
        let target = manifest
            .get_mut("target")
            .and_then(Item::as_table_mut)
            .ok_or("target table is invalid")?;
        if !table.is_empty() {
            target.insert(&name, item);
        }
        if !inner.is_empty() {
            let inner_name = inner_target_name(&name);
            if let Some(existing) = target.get_mut(&inner_name) {
                merge_target_dependencies(
                    existing
                        .as_table_mut()
                        .ok_or("generated target dependency table is invalid")?,
                    inner,
                )?;
            } else {
                let section = if inner.contains_key("dependencies") {
                    inner.get_mut("dependencies")
                } else {
                    inner.get_mut("dev-dependencies")
                }
                .and_then(Item::as_table_mut)
                .ok_or("inner target dependencies are missing")?;
                add_table_comment(section, TARGET_DEP_COMMENT);
                target.insert(&inner_name, Item::Table(inner));
            }
        }
    }
    Ok(())
}

fn inner_target_name(name: &str) -> String {
    name.strip_prefix("cfg(")
        .and_then(|name| name.strip_suffix(')'))
        .map_or_else(
            || format!("cfg(all(telekio_inner, telekio_target = {name:?}))"),
            |condition| format!("cfg(all(telekio_inner, {condition}))"),
        )
}

fn is_inner_target_name(name: &str) -> bool {
    name.starts_with("cfg(all(telekio_inner, ") && name.ends_with("))")
}

fn original_target_name(name: &str) -> Result<Option<String>, Box<dyn Error>> {
    let Some(condition) = name
        .strip_prefix("cfg(all(telekio_inner, ")
        .and_then(|name| name.strip_suffix("))"))
    else {
        return Ok(None);
    };
    if let Some(target) = condition.strip_prefix("telekio_target = ") {
        let document: DocumentMut = format!("target = {target}\n").parse()?;
        return document["target"]
            .as_str()
            .map(str::to_owned)
            .map(Some)
            .ok_or_else(|| "Telekio target triple is invalid".into());
    }
    Ok(Some(format!("cfg({condition})")))
}

fn merge_target_dependencies(target: &mut Table, mut source: Table) -> Result<(), Box<dyn Error>> {
    for section in ["dependencies", "dev-dependencies"] {
        let Some(mut incoming) = source.remove(section) else {
            continue;
        };
        if let Some(existing) = target.get_mut(section) {
            let existing = existing
                .as_table_mut()
                .ok_or("generated target dependency section is invalid")?;
            let incoming = incoming
                .as_table_mut()
                .ok_or("target dependency section is invalid")?;
            for (name, item) in std::mem::take(incoming) {
                if existing.contains_key(&name) {
                    return Err(format!("target dependency `{name}` already exists").into());
                }
                existing.insert(&name, item);
            }
        } else {
            target.insert(section, incoming);
        }
    }
    Ok(())
}

fn restore_target_dependencies(target: &mut Table) -> Result<(), Box<dyn Error>> {
    let mut names = Vec::new();
    for (name, _) in target.iter() {
        if let Some(original) = original_target_name(name)? {
            names.push((name.to_owned(), original));
        }
    }
    for (name, original) in names {
        let mut inner = target
            .remove(&name)
            .ok_or("generated target table disappeared")?;
        let inner = inner
            .as_table_mut()
            .ok_or("generated target dependency table is invalid")?;
        let mut original_item = target
            .remove(&original)
            .unwrap_or(Item::Table(Table::new()));
        let original_table = original_item
            .as_table_mut()
            .ok_or("original target table is invalid")?;
        for section in ["dependencies", "dev-dependencies"] {
            if let Some(mut item) = inner.remove(section) {
                if let Some(table) = item.as_table_mut() {
                    remove_table_comment(table, TARGET_DEP_COMMENT);
                }
                original_table.insert(section, item);
            }
        }
        if !original_table.is_empty() {
            let explicit = original_table
                .iter()
                .any(|(section, _)| !matches!(section, "dependencies" | "dev-dependencies"));
            if !explicit {
                original_table.set_implicit(true);
            }
            target.insert(&original, original_item);
        }
    }
    Ok(())
}

fn add_table_comment(table: &mut Table, comment: &str) {
    let prefix = table
        .decor()
        .prefix()
        .and_then(|prefix| prefix.as_str())
        .unwrap_or_default()
        .to_owned();
    if prefix.lines().any(|line| line.trim() == comment) {
        return;
    }
    table.decor_mut().set_prefix(format!(
        "{prefix}{}{comment}\n",
        if prefix.is_empty() || prefix.ends_with('\n') {
            ""
        } else {
            "\n"
        }
    ));
}

fn remove_table_comment(table: &mut Table, comment: &str) {
    let Some(prefix) = table
        .decor()
        .prefix()
        .and_then(|prefix| prefix.as_str())
        .map(str::to_owned)
    else {
        return;
    };
    let line = format!("{comment}\n");
    if prefix.contains(&line) {
        table.decor_mut().set_prefix(prefix.replace(&line, ""));
    }
}

fn dependency_item(name: &str, guest: bool) -> Result<Item, Box<dyn Error>> {
    let document: DocumentMut = format!(
        "[dependencies]\n{name} = {}\n",
        package_dependency(name, guest)
    )
    .parse()?;
    Ok(document["dependencies"][name].clone())
}

fn restore_dependencies(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let Some(mut target) = manifest.remove("target") else {
        return Ok(());
    };
    let original_build = manifest.remove("build-dependencies");
    let target_table = target.as_table_mut().ok_or("target table is invalid")?;
    restore_target_dependencies(target_table)?;
    let Some(mut inner) = target_table.remove(INNER_CFG) else {
        manifest.insert("target", target);
        return Ok(());
    };
    let inner = inner
        .as_table_mut()
        .ok_or("Telekio inner target is invalid")?;
    if let Some(dependencies) = inner.get_mut("dependencies").and_then(Item::as_table_mut) {
        dependencies.remove("telekio-host");
        dependencies.remove("telekio");
        remove_table_comment(dependencies, INNER_COMMENT);
    }
    for name in ["dependencies", "dev-dependencies"] {
        if let Some(item) = inner.remove(name) {
            if manifest.get(name).is_some() {
                return Err(format!("manifest already has {name}").into());
            }
            manifest.insert(name, item);
        }
    }
    if let Some(item) = original_build {
        manifest.insert("build-dependencies", item);
    }
    if !target_table.is_empty() {
        manifest.insert("target", target);
    }
    Ok(())
}

fn add_package_include(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let Some(include) = manifest["package"]
        .get_mut("include")
        .and_then(Item::as_array_mut)
    else {
        return Ok(());
    };
    if !include
        .iter()
        .any(|value| value.as_str() == Some(".telekio/**"))
    {
        include.push(".telekio/**");
    }
    Ok(())
}

fn remove_package_include(manifest: &mut DocumentMut) {
    let Some(include) = manifest["package"]
        .get_mut("include")
        .and_then(Item::as_array_mut)
    else {
        return;
    };
    let index = include
        .iter()
        .position(|value| value.as_str() == Some(".telekio/**"));
    if let Some(index) = index {
        include.remove(index);
    }
}

fn build(artifact: Artifact, root: &Path, targets: &[Target]) -> Result<(), Box<dyn Error>> {
    let command = cargo_command()?;
    let operation = command
        .get(1)
        .and_then(|argument| argument.to_str())
        .unwrap_or("build");
    let out =
        PathBuf::from(env::var_os("OUT_DIR").ok_or("OUT_DIR is unavailable")?).join("telekio");
    fs::create_dir_all(&out)?;
    let guest = prepare_artifact_guest()?;
    let verifying = matches!(operation, "check" | "clippy" | "test" | "bench" | "doc");
    let building = matches!(
        operation,
        "build" | "run" | "install" | "package" | "publish"
    );
    if !verifying && !building {
        return Err(format!("cargo {operation} is not supported").into());
    }

    let plugin = targets
        .iter()
        .find(|target| target.kind == Kind::Lib)
        .filter(|_| matches!(artifact, Artifact::Plugin));
    let exports = plugin
        .map(original_source)
        .transpose()?
        .as_deref()
        .map(plugin_exports)
        .transpose()?
        .unwrap_or_default();
    write_outer_sources(&out, targets, artifact, &exports, building)?;

    let test_backend = matches!(operation, "test" | "bench")
        .then(|| build_test_backend(&out.join("test-backend"), &command))
        .transpose()?;
    let records = out.join("artifacts");
    if records.is_dir() {
        fs::remove_dir_all(&records)?;
    }
    fs::create_dir(&records)?;
    run_inner(
        artifact,
        root,
        &out,
        &command,
        operation,
        (&guest, test_backend.as_deref()),
        targets,
    )?;
    if operation == "doc" {
        copy_docs(&out.join("inner-target"), &out)?;
    }
    let artifacts = artifacts(&records, targets)?;
    for (target, inner) in artifacts {
        link(target, artifact, &inner)?;
    }
    println!(
        "cargo::rerun-if-changed={}",
        out.join("always-missing").display()
    );
    Ok(())
}

fn cargo_command() -> Result<Vec<OsString>, Box<dyn Error>> {
    let system = System::new_all();
    let process = system
        .process(Pid::from_u32(process::id()))
        .and_then(|process| process.parent())
        .and_then(|parent| system.process(parent))
        .ok_or("parent Cargo process is unavailable")?;
    if process
        .cmd()
        .get(1)
        .is_some_and(|argument| argument == "check")
        && let Some(clippy) = process.parent().and_then(|parent| system.process(parent))
        && clippy.name().to_string_lossy().starts_with("cargo-clippy")
    {
        return Ok(clippy.cmd().to_vec());
    }
    Ok(process.cmd().to_vec())
}

fn argument<'a>(arguments: &'a [OsString], name: &str) -> Option<&'a OsStr> {
    arguments
        .iter()
        .position(|argument| argument == name)
        .and_then(|index| arguments.get(index + 1))
        .map(OsString::as_os_str)
}

fn write_inner_sources(
    out: &Path,
    targets: &[Target],
    artifact: Artifact,
) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(out)?;
    let building = cargo_command()?
        .get(1)
        .and_then(|argument| argument.to_str())
        .is_some_and(|operation| {
            matches!(
                operation,
                "build" | "run" | "install" | "package" | "publish"
            )
        });
    for target in targets {
        let source = if building && artifact_target(&target.source, artifact) {
            let (source, _) = artifact_source(&out.join("sources"), &target.source, artifact)?;
            fs::read_to_string(source)?
        } else {
            include_source(&fs::read_to_string(original_source(target)?)?)
        };
        fs::write(
            out.join(target.source.file_name().ok_or("proxy has no name")?),
            source,
        )?;
    }
    Ok(())
}

fn write_outer_sources(
    out: &Path,
    targets: &[Target],
    artifact: Artifact,
    exports: &[String],
    building: bool,
) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(out)?;
    for target in targets {
        let source = if building
            && matches!(
                (artifact, target.kind),
                (Artifact::Host, Kind::Bin | Kind::Example) | (Artifact::Plugin, Kind::Lib)
            ) {
            match artifact {
                Artifact::Host => host_proxy().to_owned(),
                Artifact::Plugin => plugin_proxy(exports),
            }
        } else {
            dummy_proxy(target).to_owned()
        };
        fs::write(
            out.join(target.source.file_name().ok_or("proxy has no name")?),
            source,
        )?;
    }
    Ok(())
}

fn host_proxy() -> &'static str {
    "// Generated by Telekio. Host artifact entry point.\n\nuse std::process::ExitCode;\n\nunsafe extern \"C-unwind\" {\n    fn telekio_inner_entry() -> u8;\n}\n\nfn main() -> ExitCode {\n    ExitCode::from(unsafe { telekio_inner_entry() })\n}\n"
}

fn plugin_proxy(exports: &[String]) -> String {
    let mut source = "// Generated by Telekio. Plugin artifact entry points.\n".to_owned();
    for export in std::iter::once("telekio_attach").chain(exports.iter().map(String::as_str)) {
        let inner = if export == "telekio_attach" {
            "telekio_inner_attach".to_owned()
        } else {
            format!("telekio_inner_{export}")
        };
        source.push_str(&format!(
            "\n#[unsafe(naked)]\n#[unsafe(no_mangle)]\npub unsafe extern \"C\" fn {export}() {{\n    #[cfg(any(target_arch = \"x86\", target_arch = \"x86_64\"))]\n    core::arch::naked_asm!(\"jmp {inner}\");\n    #[cfg(target_arch = \"aarch64\")]\n    core::arch::naked_asm!(\"b {inner}\");\n}}\n"
        ));
    }
    source
}

fn dummy_proxy(target: &Target) -> &'static str {
    match target.kind {
        Kind::Lib => "// Generated by Telekio. Library target proxy.\n",
        Kind::Test => {
            "// Generated by Telekio. Test target proxy.\n\n#[test]\nfn telekio_proxy() {}\n"
        }
        Kind::Bench if target.test => {
            "// Generated by Telekio. Benchmark target proxy.\n\n#[test]\nfn telekio_proxy() {}\n"
        }
        Kind::Bin | Kind::Example | Kind::Bench => {
            "// Generated by Telekio. Executable target proxy.\n\nfn main() {}\n"
        }
    }
}

fn artifact_source(
    out: &Path,
    proxy: &Path,
    artifact: Artifact,
) -> Result<(PathBuf, String), Box<dyn Error>> {
    let source = original_source_path(proxy)?;
    let name = format!(
        "telekio_inner_{}",
        identifier(
            proxy
                .file_stem()
                .ok_or("proxy has no file stem")?
                .to_string_lossy()
                .as_ref()
        )
    );
    let destination = out.join("sources").join(format!("{name}.rs"));
    fs::create_dir_all(destination.parent().ok_or("artifact has no parent")?)?;
    let mut source = format!(
        "// Generated by Telekio. Selected target artifact.\n\n{}",
        include_source(&fs::read_to_string(source)?)
    );
    edit::resolve_modules(
        &mut source,
        original_source_path(proxy)?
            .parent()
            .ok_or("target source has no parent")?,
    )?;
    if matches!(artifact, Artifact::Host) {
        edit::rename_function(&mut source, "main", "telekio_main")?;
        source.push_str(
            "\n#[unsafe(no_mangle)]\npub extern \"C-unwind\" fn telekio_test_handle() -> telekio::RawHandle {\n    telekio::RawHandle::empty()\n}\n\n#[unsafe(no_mangle)]\npub extern \"C-unwind\" fn telekio_inner_entry() -> u8 {\n    use std::process::{ExitCode, Termination};\n\n    let host = telekio_host::Runtime::new().unwrap();\n    let owner = host.owner();\n    assert!(telekio::attach(owner.runtime()).is_ok());\n    let code = telekio_main().report();\n    host.tokio().block_on(owner.shutdown()).unwrap();\n    (0..=u8::MAX)\n        .find(|value| code == ExitCode::from(*value))\n        .unwrap_or(1)\n}\n\nfn main() {\n    let _ = telekio_inner_entry();\n}\n",
        );
    } else {
        for export in plugin_exports(&original_source_path(proxy)?)? {
            edit::replace_attr(
                &mut source,
                edit::AttrTarget::Function(&export),
                "no_mangle",
                &format!("#[unsafe(export_name = \"telekio_inner_{export}\")]"),
            )?;
        }
        source.push_str(
            "\n#[unsafe(no_mangle)]\npub extern \"C-unwind\" fn telekio_test_handle() -> telekio::RawHandle {\n    telekio::RawHandle::empty()\n}\n\n#[unsafe(no_mangle)]\npub unsafe extern \"C\" fn telekio_inner_attach(raw: telekio::RawHandle) -> telekio::BoolResult {\n    unsafe { telekio::telekio_guest_attach(raw) }\n}\n",
        );
    }
    fs::write(&destination, source)?;
    Ok((destination, name))
}

fn build_linker(
    out: &Path,
    targets: &[Target],
    artifact: Artifact,
) -> Result<PathBuf, Box<dyn Error>> {
    let mappings = targets
        .iter()
        .filter(|target| artifact_target(&target.source, artifact))
        .map(|target| {
            Ok((
                identifier(&target.name),
                target
                    .source
                    .file_name()
                    .ok_or("target proxy has no name")?
                    .to_string_lossy()
                    .into_owned(),
            ))
        })
        .collect::<Result<Vec<_>, Box<dyn Error>>>()?;
    if mappings.is_empty() {
        return Err("no artifact targets were selected".into());
    }
    linker::build(
        out,
        &out.join("artifacts"),
        &mappings,
        env::var("TARGET").is_ok_and(|target| target.contains("windows")),
    )
}

fn run_inner(
    artifact: Artifact,
    root: &Path,
    out: &Path,
    parent: &[OsString],
    operation: &str,
    runtime: (&Path, Option<&Path>),
    targets: &[Target],
) -> Result<(), Box<dyn Error>> {
    let (guest, backend) = runtime;
    let target_dir = out.join("inner-target");
    let lock = out.join("inner-lock/Cargo.lock");
    let cargo = env::var_os("CARGO").ok_or("CARGO is unavailable")?;
    fs::create_dir_all(lock.parent().ok_or("inner lock has no parent")?)?;
    fs::create_dir_all(&target_dir)?;
    fs::write(target_dir.join(".telekio-inner"), [])?;

    let building = matches!(
        operation,
        "build" | "run" | "install" | "package" | "publish"
    );
    let linker = building.then(|| build_linker(out, targets, artifact));
    let linker = linker.transpose()?;
    let mut flags = env::var_os("CARGO_ENCODED_RUSTFLAGS")
        .map(|flags| flags.to_string_lossy().into_owned())
        .unwrap_or_default();
    let mut append_flag = |flag: &str| {
        if !flags.is_empty() {
            flags.push('\u{1f}');
        }
        flags.push_str(flag);
    };
    append_flag("--cfg");
    append_flag("telekio_inner");
    append_flag("--cfg");
    append_flag(&format!(
        "telekio_target=\"{}\"",
        env::var("TARGET").map_err(|_| "TARGET is unavailable")?
    ));
    if let Some(linker) = &linker {
        append_flag("-C");
        append_flag(&format!("linker={}", linker.display()));
    }
    if let Some(backend) = backend {
        append_flag("-C");
        append_flag(&format!("link-arg={}", backend.display()));
        append_flag("-C");
        append_flag(&format!(
            "link-arg={}",
            if env::var("TARGET").is_ok_and(|target| target.contains("windows")) {
                "/FORCE:MULTIPLE"
            } else {
                "-Wl,--allow-multiple-definition"
            }
        ));
        for library in
            native_libraries(env::var("TARGET").is_ok_and(|target| target.contains("windows")))
        {
            append_flag("-C");
            append_flag(&format!("link-arg={library}"));
        }
    }

    let config = [
        format!("resolver.lockfile-path={:?}", lock),
        format!("patch.crates-io.tokio.path={:?}", guest),
    ];
    if !lock.is_file() {
        let mut command = Command::new(&cargo);
        command
            .current_dir(root)
            .arg("generate-lockfile")
            .arg("--manifest-path")
            .arg(root.join("Cargo.toml"));
        for option in &config {
            command.arg("--config").arg(option);
        }
        command
            .args(config_options(parent))
            .env("CARGO_ENCODED_RUSTFLAGS", &flags)
            .env_remove("RUSTFLAGS");
        let status = command.status()?;
        if !status.success() {
            return Err(format!("inner cargo generate-lockfile failed with {status}").into());
        }
    }

    let command_name = if matches!(operation, "run" | "install" | "package" | "publish") {
        "build"
    } else {
        operation
    };
    let mut command = Command::new(&cargo);
    command
        .current_dir(root)
        .arg(command_name)
        .arg("--manifest-path")
        .arg(root.join("Cargo.toml"))
        .arg("--target-dir")
        .arg(&target_dir);
    for option in &config {
        command.arg("--config").arg(option);
    }
    command
        .args(inner_options(parent, operation)?)
        .env("CARGO_ENCODED_RUSTFLAGS", flags)
        .env_remove("RUSTFLAGS");
    let status = command.status()?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("inner cargo {operation} failed with {status}").into())
    }
}

fn inner_options(parent: &[OsString], operation: &str) -> Result<Vec<OsString>, Box<dyn Error>> {
    let distribution = matches!(operation, "install" | "package" | "publish");
    let mut options = Vec::new();
    let mut index = 2;
    while index < parent.len() {
        let argument = parent[index].to_string_lossy();
        if argument == "--" && matches!(operation, "run" | "install" | "package" | "publish") {
            break;
        }
        if matches!(argument.as_ref(), "--manifest-path" | "--target-dir") {
            index += 2;
            continue;
        }
        if argument.starts_with("--manifest-path=") || argument.starts_with("--target-dir=") {
            index += 1;
            continue;
        }
        if distribution {
            if let Some(takes_value) = outer_option(operation, &argument) {
                index += usize::from(takes_value) + 1;
                continue;
            }
            if !argument.starts_with('-') {
                index += 1;
                continue;
            }
            if common_option_takes_value(&argument)
                && !argument.contains('=')
                && let Some(value) = parent.get(index + 1)
            {
                options.extend([parent[index].clone(), value.clone()]);
                index += 2;
                continue;
            }
        }
        options.push(parent[index].clone());
        index += 1;
    }
    if matches!(operation, "run" | "install" | "package" | "publish")
        && env::var("PROFILE").as_deref() == Ok("release")
        && !options
            .iter()
            .any(|argument| matches!(argument.to_str(), Some("--release" | "--profile")))
    {
        options.push("--release".into());
    }
    if !options.iter().any(|argument| argument == "--target") {
        options.extend([
            OsString::from("--target"),
            env::var_os("TARGET").ok_or("TARGET is unavailable")?,
        ]);
    }
    Ok(options)
}

fn config_options(arguments: &[OsString]) -> Vec<OsString> {
    let mut options = Vec::new();
    let mut index = 2;
    while index < arguments.len() {
        let argument = arguments[index].to_string_lossy();
        if argument == "--config" {
            if let Some(value) = arguments.get(index + 1) {
                options.extend([arguments[index].clone(), value.clone()]);
            }
            index += 2;
        } else {
            if argument.starts_with("--config=") {
                options.push(arguments[index].clone());
            }
            index += 1;
        }
    }
    options
}

fn outer_option(operation: &str, argument: &str) -> Option<bool> {
    let (flags, values): (&[&str], &[&str]) = match operation {
        "install" => (
            &["--list", "--force", "--no-track", "--debug", "--dry-run"],
            &[
                "--root",
                "--path",
                "--git",
                "--branch",
                "--tag",
                "--rev",
                "--version",
                "--registry",
                "--index",
            ],
        ),
        "package" => (
            &["--allow-dirty", "--no-verify", "--no-metadata", "--list"],
            &[],
        ),
        "publish" => (
            &["--allow-dirty", "--no-verify", "--dry-run"],
            &["--token", "--registry", "--index"],
        ),
        _ => return None,
    };
    if flags.contains(&argument) {
        return Some(false);
    }
    if values.contains(&argument) {
        return Some(true);
    }
    values
        .iter()
        .any(|option| argument.starts_with(&format!("{option}=")))
        .then_some(false)
}

fn common_option_takes_value(argument: &str) -> bool {
    matches!(
        argument,
        "--package"
            | "-p"
            | "--exclude"
            | "--jobs"
            | "-j"
            | "--target"
            | "--profile"
            | "--features"
            | "-F"
            | "--bin"
            | "--example"
            | "--color"
            | "--message-format"
            | "--config"
            | "-Z"
    )
}

fn artifact_target(proxy: &Path, artifact: Artifact) -> bool {
    let kind = proxy_kind(proxy);
    matches!(
        (artifact, kind),
        (Artifact::Host, Some(Kind::Bin | Kind::Example)) | (Artifact::Plugin, Some(Kind::Lib))
    )
}

fn proxy_kind(proxy: &Path) -> Option<Kind> {
    let name = proxy.file_name()?.to_str()?;
    let name = ["inferred-", "declared-", "explicit-"]
        .into_iter()
        .find_map(|prefix| name.strip_prefix(prefix))?;
    [Kind::Lib, Kind::Bin, Kind::Test, Kind::Example, Kind::Bench]
        .into_iter()
        .find(|kind| name.starts_with(&format!("{}-", kind.key())))
}

fn original_source(target: &Target) -> Result<PathBuf, Box<dyn Error>> {
    original_source_path(&target.source)
}

fn original_source_path(proxy: &Path) -> Result<PathBuf, Box<dyn Error>> {
    let source = fs::read_to_string(proxy)?;
    let path = source
        .lines()
        .find_map(|line| line.trim().strip_prefix("#[path = \"")?.strip_suffix("\"]"))
        .ok_or_else(|| format!("{} has no original target path", proxy.display()))?;
    Ok(fs::canonicalize(
        proxy.parent().ok_or("proxy has no parent")?.join(path),
    )?)
}

fn build_test_backend(out: &Path, parent: &[OsString]) -> Result<PathBuf, Box<dyn Error>> {
    fs::create_dir_all(out.join("src"))?;
    fs::write(
        out.join("Cargo.toml"),
        format!(
            "# Generated by Telekio. Host test runtime.\n[package]\nname = \"telekio-test-backend\"\nversion = \"0.0.0\"\nedition = \"2024\"\n\n[workspace]\n\n[lib]\ncrate-type = [\"staticlib\"]\n\n[dependencies]\ntelekio = {}\ntelekio-host = {}\n",
            package_dependency("telekio", false),
            package_dependency("telekio-host", false)
        ),
    )?;
    fs::write(
        out.join("src/lib.rs"),
        "// Generated by Telekio. Provides the host test runtime.\n\nuse std::sync::OnceLock;\n\nstatic OWNER: OnceLock<telekio_host::Owner> = OnceLock::new();\n\n#[unsafe(no_mangle)]\npub extern \"C-unwind\" fn telekio_test_handle() -> telekio::RawHandle {\n    OWNER\n        .get_or_init(|| telekio_host::Runtime::new().unwrap().owner())\n        .runtime()\n        .into_abi()\n}\n",
    )?;
    run_helper(out, parent)?;
    let output = profile_output(&out.join("target"), parent);
    let (prefix, extension) = if env::var("TARGET").is_ok_and(|target| target.contains("windows")) {
        ("", "lib")
    } else {
        ("lib", "a")
    };
    let artifact = output.join(format!("{prefix}telekio_test_backend.{extension}"));
    artifact
        .is_file()
        .then_some(artifact)
        .ok_or_else(|| "test backend static library was not produced".into())
}

fn run_helper(root: &Path, parent: &[OsString]) -> Result<(), Box<dyn Error>> {
    let cargo = env::var_os("CARGO").ok_or("CARGO is unavailable")?;
    let status = Command::new(cargo)
        .current_dir(root)
        .arg("build")
        .arg("--manifest-path")
        .arg(root.join("Cargo.toml"))
        .arg("--target-dir")
        .arg(root.join("target"))
        .args(helper_options(parent)?)
        .status()?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("helper Cargo failed with {status}").into())
    }
}

fn helper_options(parent: &[OsString]) -> Result<Vec<OsString>, Box<dyn Error>> {
    let mut options = Vec::new();
    if env::var("PROFILE").as_deref() == Ok("release") {
        options.push("--release".into());
    }
    if parent
        .iter()
        .any(|argument| matches!(argument.to_str(), Some("-v" | "-vv" | "--verbose")))
    {
        options.push("--verbose".into());
    }
    options.extend([
        OsString::from("--target"),
        argument(parent, "--target")
            .map(OsStr::to_owned)
            .or_else(|| env::var_os("TARGET"))
            .ok_or("TARGET is unavailable")?,
    ]);
    Ok(options)
}

fn package_dependency(name: &str, guest: bool) -> String {
    let mut fields = vec![format!("version = \"={}\"", env!("CARGO_PKG_VERSION"))];
    if let Some(path) = package_sibling(name) {
        fields.push(format!("path = {:?}", cargo_path(&path)));
    }
    if guest {
        fields.push("features = [\"guest\"]".to_owned());
    }
    format!("{{ {} }}", fields.join(", "))
}

fn package_sibling(name: &str) -> Option<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|parent| {
            [
                parent.join(name),
                parent.join(format!("{name}-{}", env!("CARGO_PKG_VERSION"))),
            ]
            .into_iter()
            .find(|path| path.join("Cargo.toml").is_file())
        })
}

fn profile_output(root: &Path, parent: &[OsString]) -> PathBuf {
    let mut output = root.to_owned();
    output.push(
        argument(parent, "--target")
            .map(OsStr::to_owned)
            .or_else(|| env::var_os("TARGET"))
            .expect("TARGET is unavailable"),
    );
    output.push(env::var("PROFILE").unwrap_or_else(|_| "debug".to_owned()));
    output
}

fn copy_docs(inner: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
    let source = inner
        .join(env::var_os("TARGET").ok_or("TARGET is unavailable")?)
        .join("doc");
    let destination = out
        .ancestors()
        .nth(5)
        .ok_or("outer target directory is unavailable")?
        .join("doc/inner");
    copy_directory(&source, &destination)
}

fn copy_directory(source: &Path, destination: &Path) -> Result<(), Box<dyn Error>> {
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let target = destination.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_directory(&entry.path(), &target)?;
        } else {
            fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}

type ArtifactRecord<'a> = (&'a Target, Vec<OsString>);

fn artifacts<'a>(
    directory: &Path,
    targets: &'a [Target],
) -> Result<Vec<ArtifactRecord<'a>>, Box<dyn Error>> {
    let mut artifacts = Vec::new();
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        if entry
            .path()
            .extension()
            .is_none_or(|extension| extension != "record")
        {
            continue;
        }
        let proxy = entry
            .path()
            .file_stem()
            .ok_or("artifact record has no proxy name")?
            .to_owned();
        let target = targets
            .iter()
            .find(|target| target.source.file_name() == Some(proxy.as_os_str()))
            .ok_or_else(|| {
                format!(
                    "artifact record `{}` has no target",
                    proxy.to_string_lossy()
                )
            })?;
        let inputs = linker::read_record(&entry.path())?;
        artifacts.push((target, inputs));
    }
    Ok(artifacts)
}

fn link(target: &Target, artifact: Artifact, arguments: &[OsString]) -> Result<(), Box<dyn Error>> {
    let directive = match target.kind {
        Kind::Bin => format!("cargo::rustc-link-arg-bin={}=", target.name),
        Kind::Example => "cargo::rustc-link-arg-examples=".to_owned(),
        Kind::Lib if matches!(artifact, Artifact::Plugin) => {
            "cargo::rustc-link-arg-cdylib=".to_owned()
        }
        _ => return Err("selected target cannot produce a final artifact".into()),
    };
    for argument in arguments {
        println!(
            "{directive}{}",
            argument
                .to_str()
                .ok_or("linker argument is not valid Unicode")?
        );
    }
    println!(
        "{directive}{}",
        if env::var("TARGET").is_ok_and(|target| target.contains("windows")) {
            "/FORCE:MULTIPLE"
        } else {
            "-Wl,--allow-multiple-definition"
        }
    );
    Ok(())
}

fn plugin_exports(path: &Path) -> Result<Vec<String>, Box<dyn Error>> {
    let source = fs::read_to_string(path)?;
    let parsed = SourceFile::parse(&source, Edition::CURRENT);
    if !parsed.errors().is_empty() {
        return Err(format!("plugin source has syntax errors: {:?}", parsed.errors()).into());
    }
    Ok(parsed
        .tree()
        .syntax()
        .children()
        .filter_map(ast::Fn::cast)
        .filter(|function| edit::has_attr(function, "no_mangle"))
        .filter_map(|function| function.name().map(|name| name.text().to_string()))
        .collect())
}

fn native_libraries(windows: bool) -> &'static [&'static str] {
    if windows {
        &[
            "kernel32.lib",
            "ntdll.lib",
            "userenv.lib",
            "ws2_32.lib",
            "dbghelp.lib",
            "/defaultlib:msvcrt",
        ]
    } else {
        &[
            "-lgcc_s",
            "-lutil",
            "-lrt",
            "-lpthread",
            "-lm",
            "-ldl",
            "-lc",
        ]
    }
}

fn identifier(name: &str) -> String {
    name.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect()
}

fn package_root() -> Result<PathBuf, Box<dyn Error>> {
    let manifest = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").ok_or("CARGO_MANIFEST_DIR is unavailable")?,
    );
    Ok(fs::canonicalize(manifest)?)
}

fn targets(root: &Path) -> Result<Vec<Target>, Box<dyn Error>> {
    let cargo = env::var_os("CARGO").ok_or("CARGO is unavailable")?;
    let output = Command::new(cargo)
        .args(["metadata", "--no-deps", "--format-version", "1"])
        .arg("--manifest-path")
        .arg(root.join("Cargo.toml"))
        .output()?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        )
        .into());
    }
    let metadata: Json = serde_json::from_slice(&output.stdout)?;
    let manifest = fs::canonicalize(root.join("Cargo.toml"))?;
    let package = metadata["packages"]
        .as_array()
        .and_then(|packages| {
            packages.iter().find(|package| {
                package["manifest_path"]
                    .as_str()
                    .and_then(|path| fs::canonicalize(path).ok())
                    .is_some_and(|path| path == manifest)
            })
        })
        .ok_or("cargo metadata omitted the artifact package")?;
    let mut targets = Vec::new();
    for target in package["targets"]
        .as_array()
        .ok_or("cargo metadata returned invalid targets")?
    {
        let kinds = target["kind"]
            .as_array()
            .ok_or("target has invalid kinds")?;
        let kind = if kinds.iter().any(|kind| kind == "custom-build") {
            continue;
        } else if kinds.iter().any(|kind| kind == "bin") {
            Kind::Bin
        } else if kinds.iter().any(|kind| kind == "test") {
            Kind::Test
        } else if kinds.iter().any(|kind| kind == "example") {
            Kind::Example
        } else if kinds.iter().any(|kind| kind == "bench") {
            Kind::Bench
        } else {
            Kind::Lib
        };
        targets.push(Target {
            name: target["name"]
                .as_str()
                .ok_or("target has no name")?
                .to_owned(),
            kind,
            source: fs::canonicalize(
                target["src_path"]
                    .as_str()
                    .ok_or("target has no source path")?,
            )?,
            test: target["test"].as_bool().unwrap_or(false),
        });
    }
    Ok(targets)
}

fn generated(path: &Path) -> bool {
    path.parent()
        .is_some_and(|parent| parent.file_name().is_some_and(|name| name == DIRECTORY))
        && fs::read_to_string(path).is_ok_and(|source| source.starts_with(GENERATED))
}

fn target_origin(
    manifest: &DocumentMut,
    root: &Path,
    target: &Target,
) -> Result<Origin, Box<dyn Error>> {
    let Some(table) = target_table(manifest, root, target)? else {
        return Ok(Origin::Inferred);
    };
    Ok(if table.contains_key("path") {
        Origin::Explicit
    } else {
        Origin::Declared
    })
}

fn target_table<'a>(
    manifest: &'a DocumentMut,
    root: &Path,
    target: &Target,
) -> Result<Option<&'a Table>, Box<dyn Error>> {
    if target.kind == Kind::Lib {
        return Ok(manifest.get("lib").and_then(Item::as_table));
    }
    let Some(targets) = manifest
        .get(target.kind.key())
        .and_then(Item::as_array_of_tables)
    else {
        return Ok(None);
    };
    Ok(targets.iter().find(|table| {
        table
            .get("name")
            .and_then(Item::as_str)
            .is_some_and(|name| name == target.name)
            || table
                .get("path")
                .and_then(Item::as_str)
                .map(|path| root.join(path))
                .and_then(|path| fs::canonicalize(path).ok())
                .is_some_and(|path| path == target.source)
    }))
}

fn set_target_path(
    manifest: &mut DocumentMut,
    root: &Path,
    target: &Target,
    proxy: &Path,
) -> Result<(), Box<dyn Error>> {
    let path = cargo_path(proxy.strip_prefix(root)?);
    if target.kind == Kind::Lib {
        if manifest.get("lib").is_none() {
            manifest.insert("lib", Item::Table(Table::new()));
        }
        let table = manifest["lib"]
            .as_table_mut()
            .ok_or("lib target is invalid")?;
        table.insert("path", value(path));
        comment_path(table)?;
        return Ok(());
    }

    if manifest.get(target.kind.key()).is_none() {
        manifest.insert(target.kind.key(), Item::ArrayOfTables(ArrayOfTables::new()));
    }
    let targets = manifest[target.kind.key()]
        .as_array_of_tables_mut()
        .ok_or("target list is invalid")?;
    let index = targets.iter().position(|table| {
        table
            .get("name")
            .and_then(Item::as_str)
            .is_some_and(|name| name == target.name)
            || table
                .get("path")
                .and_then(Item::as_str)
                .map(|path| root.join(path))
                .and_then(|path| fs::canonicalize(path).ok())
                .is_some_and(|path| path == target.source)
    });
    let table = if let Some(index) = index {
        targets.get_mut(index).ok_or("target disappeared")?
    } else {
        let mut table = Table::new();
        table.insert("name", value(&target.name));
        targets.push(table);
        targets.iter_mut().last().ok_or("target was not inserted")?
    };
    table.insert("path", value(path));
    comment_path(table)?;
    Ok(())
}

fn comment_path(table: &mut Table) -> Result<(), Box<dyn Error>> {
    table
        .key_mut("path")
        .ok_or("target path is unavailable")?
        .leaf_decor_mut()
        .set_prefix(format!("\n{TARGET_COMMENT}\n"));
    Ok(())
}

fn restore_target(
    manifest: &mut DocumentMut,
    root: &Path,
    target: &Target,
) -> Result<(), Box<dyn Error>> {
    let proxy = fs::read_to_string(&target.source)?;
    let original = proxy
        .lines()
        .find_map(|line| line.trim().strip_prefix("#[path = \"")?.strip_suffix("\"]"))
        .ok_or_else(|| format!("{} has no original target path", target.source.display()))?;
    let original = cargo_path(
        target
            .source
            .parent()
            .ok_or("proxy has no parent")?
            .join(original)
            .canonicalize()?
            .strip_prefix(root)?,
    );
    let origin = proxy_origin(&target.source)?;

    if target.kind == Kind::Lib {
        match origin {
            Origin::Inferred => {
                manifest.remove("lib");
            }
            Origin::Declared => {
                manifest["lib"]
                    .as_table_mut()
                    .ok_or("lib target is invalid")?
                    .remove("path");
            }
            Origin::Explicit => {
                manifest["lib"]["path"] = value(original);
            }
        }
        return Ok(());
    }

    let targets = manifest[target.kind.key()]
        .as_array_of_tables_mut()
        .ok_or("target list is invalid")?;
    let index = targets
        .iter()
        .position(|table| {
            table
                .get("path")
                .and_then(Item::as_str)
                .is_some_and(|path| root.join(path) == target.source)
        })
        .ok_or("proxy target was not found")?;
    match origin {
        Origin::Inferred => {
            targets.remove(index);
        }
        Origin::Declared => {
            targets
                .get_mut(index)
                .ok_or("target disappeared")?
                .remove("path");
        }
        Origin::Explicit => {
            targets
                .get_mut(index)
                .ok_or("target disappeared")?
                .insert("path", value(original));
        }
    }
    if targets.is_empty() {
        manifest.remove(target.kind.key());
    }
    Ok(())
}

fn proxy_path(root: &Path, target: &Target, origin: Origin) -> PathBuf {
    let origin = match origin {
        Origin::Inferred => "inferred",
        Origin::Declared => "declared",
        Origin::Explicit => "explicit",
    };
    let name = target
        .name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || matches!(character, '-' | '_') {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    root.join(DIRECTORY)
        .join(format!("{origin}-{}-{name}.rs", target.kind.key()))
}

fn proxy_source(root: &Path, target: &Target, proxy: &Path) -> Result<String, Box<dyn Error>> {
    let original = target.source.strip_prefix(root)?;
    let proxy = proxy
        .file_name()
        .ok_or("proxy has no name")?
        .to_string_lossy();
    let single = format!("include!(concat!(env!(\"OUT_DIR\"), \"/telekio/{proxy}\"));");
    let include = if single.len() <= 100 {
        single
    } else {
        format!("include!(concat!(\n    env!(\"OUT_DIR\"),\n    \"/telekio/{proxy}\"\n));")
    };
    let docs = (target.kind == Kind::Lib).then(|| {
        format!(
            "#![doc = \"<meta http-equiv=\\\"refresh\\\" content=\\\"0; url=../inner/{}/index.html\\\">\"]\n\n",
            identifier(&target.name)
        )
    });
    Ok(format!(
        "{GENERATED} Links this target to its Telekio artifact.\n\n{}#[cfg(any())]\n#[path = \"../{}\"]\nmod original;\n\n{include}\n",
        docs.unwrap_or_default(),
        cargo_path(original)
    ))
}

fn proxy_origin(path: &Path) -> Result<Origin, Box<dyn Error>> {
    let name = path
        .file_name()
        .ok_or("proxy has no name")?
        .to_string_lossy();
    if name.starts_with("inferred-") {
        Ok(Origin::Inferred)
    } else if name.starts_with("declared-") {
        Ok(Origin::Declared)
    } else if name.starts_with("explicit-") {
        Ok(Origin::Explicit)
    } else {
        Err(format!("unknown Telekio proxy name `{name}`").into())
    }
}

fn build_script(manifest: &DocumentMut, root: &Path) -> Result<PathBuf, Box<dyn Error>> {
    let path = manifest["package"]
        .get("build")
        .and_then(Item::as_str)
        .unwrap_or("build.rs");
    Ok(root.join(path))
}

fn remove_build_dependency(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let Some(dependencies) = manifest
        .get_mut("build-dependencies")
        .and_then(Item::as_table_mut)
    else {
        return Err("Telekio is not a build dependency".into());
    };
    let names = dependencies
        .iter()
        .filter(|(name, dependency)| {
            *name == "telekio-build"
                || dependency
                    .get("package")
                    .and_then(Item::as_str)
                    .is_some_and(|package| package == "telekio-build")
        })
        .map(|(name, _)| name.to_owned())
        .collect::<Vec<_>>();
    if names.len() != 1 {
        return Err("expected one telekio-build build dependency".into());
    }
    dependencies.remove(&names[0]);
    if dependencies.is_empty() {
        manifest.remove("build-dependencies");
    }
    Ok(())
}

fn remove_action(source: &str) -> Result<String, Box<dyn Error>> {
    let parsed = SourceFile::parse(source, Edition::CURRENT);
    if !parsed.errors().is_empty() {
        return Err(format!("build script has syntax errors: {:?}", parsed.errors()).into());
    }
    let calls = parsed
        .tree()
        .syntax()
        .descendants()
        .filter_map(ast::MacroCall::cast)
        .filter(|call| {
            call.path()
                .is_some_and(|path| path.syntax().text().to_string().ends_with("remove"))
        })
        .collect::<Vec<_>>();
    let [call] = calls.as_slice() else {
        return Err(format!("expected one remove! call, found {}", calls.len()).into());
    };
    let statement = call
        .syntax()
        .ancestors()
        .find_map(ast::ExprStmt::cast)
        .ok_or("remove! is not an expression statement")?;
    let range = statement.syntax().text_range();
    let start: usize = range.start().into();
    let end: usize = range.end().into();
    let line_start = source[..start].rfind('\n').map_or(0, |index| index + 1);
    let line_end = source[end..]
        .find('\n')
        .map_or(source.len(), |index| end + index + 1);
    if !source[line_start..start].trim().is_empty() || !source[end..line_end].trim().is_empty() {
        return Err("remove! must occupy its own line".into());
    }
    Ok(format!("{}{}", &source[..line_start], &source[line_end..]))
}

fn remove_generated(directory: &Path) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        if !entry.file_type()?.is_file()
            || !fs::read_to_string(entry.path())?.starts_with(GENERATED)
        {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    fs::remove_dir_all(directory)?;
    Ok(())
}

fn cargo_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

impl Kind {
    fn key(self) -> &'static str {
        match self {
            Self::Lib => "lib",
            Self::Bin => "bin",
            Self::Test => "test",
            Self::Example => "example",
            Self::Bench => "bench",
        }
    }
}
