use std::{error::Error, fs, path::Path};

use toml_edit::{DocumentMut, Item};

use crate::guest::{Role, prepare_patch};

const DIRECTORY: &str = ".telekio/tokio";
const PATCH_PATH: &str = ".telekio/tokio";
const GENERATED: &str = "Generated by Telekio.";

pub fn init_project(manifest: &Path, role: Role, offline: bool) -> Result<(), Box<dyn Error>> {
    let root = manifest.parent().ok_or("manifest has no parent")?;
    let mut document = fs::read_to_string(manifest)?.parse::<DocumentMut>()?;
    if let Some(path) = patch_path(&document)
        && path != PATCH_PATH
    {
        return Err(format!("Tokio is already patched from `{path}`").into());
    }
    let directory = root.join(DIRECTORY);
    validate_destination(&directory)?;
    prepare_patch(&directory, role, offline)?;
    set_patch(&mut document)?;
    fs::write(manifest, document.to_string())?;
    Ok(())
}

pub fn remove_project(manifest: &Path) -> Result<(), Box<dyn Error>> {
    let root = manifest.parent().ok_or("manifest has no parent")?;
    let mut document = fs::read_to_string(manifest)?.parse::<DocumentMut>()?;
    if patch_path(&document).as_deref() != Some(PATCH_PATH) {
        return Err("this package does not use its Telekio patch".into());
    }
    let directory = root.join(DIRECTORY);
    validate_patch(&directory)?;
    validate_parent(directory.parent().ok_or("patch has no parent")?)?;
    remove_patch(&mut document)?;

    fs::write(manifest, document.to_string())?;
    fs::remove_dir_all(directory.parent().ok_or("patch has no parent")?)?;
    Ok(())
}

fn patch_path(manifest: &DocumentMut) -> Option<String> {
    manifest
        .get("patch")?
        .get("crates-io")?
        .get("tokio")?
        .get("path")?
        .as_str()
        .map(str::to_owned)
}

fn set_patch(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let patch: DocumentMut =
        format!("[patch.crates-io]\ntokio = {{ path = {PATCH_PATH:?} }}\n").parse()?;
    if manifest.get("patch").is_none() {
        let mut table = toml_edit::Table::new();
        table.set_implicit(true);
        manifest.insert("patch", Item::Table(table));
    }
    let patches = manifest["patch"]
        .as_table_mut()
        .ok_or("patch is not a table")?;
    if patches.get("crates-io").is_none() {
        patches.insert("crates-io", Item::Table(Default::default()));
    }
    patches["crates-io"]
        .as_table_mut()
        .ok_or("patch.crates-io is not a table")?
        .insert("tokio", patch["patch"]["crates-io"]["tokio"].clone());
    Ok(())
}

fn remove_patch(manifest: &mut DocumentMut) -> Result<(), Box<dyn Error>> {
    let patches = manifest["patch"]
        .as_table_mut()
        .ok_or("patch is not a table")?;
    let crates_io = patches["crates-io"]
        .as_table_mut()
        .ok_or("patch.crates-io is not a table")?;
    crates_io.remove("tokio");
    if crates_io.is_empty() {
        patches.remove("crates-io");
    }
    if patches.is_empty() {
        manifest.remove("patch");
    }
    Ok(())
}

fn validate_destination(directory: &Path) -> Result<(), Box<dyn Error>> {
    let parent = directory.parent().ok_or("patch has no parent")?;
    if parent.exists() {
        validate_parent(parent)?;
    }
    if directory.exists() {
        validate_patch(directory)?;
    }
    Ok(())
}

fn validate_parent(directory: &Path) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        if entry.file_name() != "tokio" {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    Ok(())
}

fn validate_patch(directory: &Path) -> Result<(), Box<dyn Error>> {
    for path in [
        directory.join("Cargo.toml"),
        directory.join("build.rs"),
        directory.join("src/lib.rs"),
    ] {
        let source = fs::read_to_string(&path).map_err(|error| {
            format!("could not read generated file {}: {error}", path.display())
        })?;
        if !source.lines().any(|line| line.contains(GENERATED)) {
            return Err(format!("{} is not generated by Telekio", path.display()).into());
        }
    }
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        if entry.file_name() != "Cargo.toml"
            && entry.file_name() != "build.rs"
            && entry.file_name() != "src"
        {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    for entry in fs::read_dir(directory.join("src"))? {
        let entry = entry?;
        if entry.file_name() != "lib.rs" {
            return Err(format!("{} is not generated by Telekio", entry.path().display()).into());
        }
    }
    Ok(())
}
