[package]
name = "telekio-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Host runtime backend for Telekio"

[dependencies]
telekio = { version = "=0.1.0", path = "../telekio" }
tokio = { version = "=0.1.0", path = "../telekio-tokio", package = "telekio-tokio", features = ["net", "rt", "rt-multi-thread", "schedule-latency", "signal", "sync", "test-util", "time"] }

[target."cfg(unix)".dependencies]
libc = "0.2.168"
