use std::{
    env,
    error::Error,
    ffi::{OsStr, OsString},
    fs::{self, File},
    path::{Path, PathBuf},
    process::{self, Command},
};

use telekio_build::Role;

const GENERATED: &str = "Generated by Telekio.";

struct ProjectInfo {
    packages: Vec<PackageInfo>,
    workspace_selection: bool,
    workspace_mixed: bool,
}

struct PackageInfo {
    name: String,
    role: Role,
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum CommandKind {
    Packages,
    Workspace,
    Single,
    Output,
    Plain,
}

enum PatchState {
    Selected,
    Unused,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("telekio: {error}");
        process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let mut arguments = env::args_os().skip(1).collect::<Vec<_>>();
    let command = arguments
        .first()
        .and_then(|argument| argument.to_str())
        .ok_or("usage: telekio <cargo|init|remove> [arguments]")?
        .to_owned();
    if matches!(command.as_str(), "--help" | "-h") {
        println!("Usage: telekio <cargo|init|remove> [arguments]");
        return Ok(());
    }
    if matches!(command.as_str(), "--version" | "-V") {
        println!("telekio {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }
    let cargo = OsString::from("cargo");
    if matches!(command.as_str(), "init" | "remove") {
        arguments.remove(0);
        let manifest = project_manifest(&cargo, &arguments)?.ok_or("Cargo.toml was not found")?;
        if command == "init" {
            let mut workspace = arguments.clone();
            workspace.push(OsString::from("--workspace"));
            let info = project_info(&cargo, &workspace, &manifest)?;
            let roles = info.roles();
            if roles.len() > 1 {
                return Err("a persistent Tokio patch cannot represent both Telekio host and guest packages; use `telekio cargo` for this workspace".into());
            }
            telekio_build::init_project(
                &manifest,
                roles.first().copied().unwrap_or(Role::Host),
                offline(&arguments),
            )?;
        } else {
            telekio_build::remove_project(&manifest)?;
        }
        return Ok(());
    }
    if command != "cargo" {
        return Err("usage: telekio <cargo|init|remove> [arguments]".into());
    }
    arguments.remove(0);
    let interpreted = expand_alias(&cargo, &arguments)?;
    let operation = operation(&interpreted);
    if operation.is_some_and(|operation| command_kind(operation) == CommandKind::Plain) {
        return exit(cargo_status(&cargo, &arguments, None)?);
    }
    let manifest = project_manifest(&cargo, &interpreted)?;
    let Some(manifest) = manifest else {
        let config = prepare_config(Role::Host, false, offline(&interpreted))?;
        return exit(cargo_status(&cargo, &interpreted, Some(&config))?);
    };
    let info = project_info(&cargo, &interpreted, &manifest)?;
    let roles = info.roles();
    if roles.len() <= 1 {
        let role = roles.first().copied().unwrap_or(Role::Host);
        let config = prepare_config(
            role,
            role == Role::Guest && info.workspace_mixed,
            offline(&interpreted),
        )?;
        let selected = verify_patch(
            &cargo,
            &interpreted,
            &manifest,
            &config,
            &info.package_names(),
        )?;
        return match selected {
            PatchState::Selected => exit(cargo_status(&cargo, &interpreted, Some(&config))?),
            PatchState::Unused => exit(cargo_status(&cargo, &arguments, None)?),
        };
    }

    let operation = operation.ok_or(
        "this Cargo extension cannot determine mixed Telekio package selection; select one role",
    )?;
    match command_kind(operation) {
        CommandKind::Packages if info.workspace_selection => {
            let (host, guest) = info.groups();
            run_groups(&cargo, &interpreted, &manifest, &host, &guest, true)
        }
        CommandKind::Workspace => {
            let (host, guest) = info.groups();
            run_groups(&cargo, &interpreted, &manifest, &host, &guest, false)
        }
        CommandKind::Packages if operation == "tree" => {
            let (host, guest) = info.groups();
            run_groups(&cargo, &interpreted, &manifest, &host, &guest, false)
        }
        CommandKind::Single => Err(format!(
            "`cargo {operation}` requires packages from one Telekio role; select one package"
        )
        .into()),
        CommandKind::Output | CommandKind::Packages => Err(format!(
            "`cargo {operation}` cannot combine Telekio host and guest dependency graphs; select one package role"
        )
        .into()),
        CommandKind::Plain => unreachable!(),
    }
}

fn run_groups(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
    host: &[String],
    guest: &[String],
    select_packages: bool,
) -> Result<(), Box<dyn Error>> {
    let mut failed = None;
    for (role, packages) in [(Role::Host, host), (Role::Guest, guest)] {
        if packages.is_empty() {
            continue;
        }
        let arguments = if select_packages {
            package_arguments(arguments, packages)
        } else {
            arguments.to_vec()
        };
        let config = prepare_config(role, true, offline(&arguments))?;
        let selected = verify_patch(cargo, &arguments, manifest, &config, packages)?;
        let status = cargo_status(
            cargo,
            &arguments,
            matches!(selected, PatchState::Selected).then_some(config.as_path()),
        )?;
        if !status.success() {
            if !has_option(&arguments, "--keep-going") && !has_option(&arguments, "--no-fail-fast")
            {
                return exit(status);
            }
            failed.get_or_insert(status);
        }
    }
    if let Some(status) = failed {
        exit(status)
    } else {
        Ok(())
    }
}

fn verify_patch(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
    config: &Path,
    packages: &[String],
) -> Result<PatchState, Box<dyn Error>> {
    if operation(arguments) == Some("update") {
        return Ok(PatchState::Selected);
    }
    patch_selected(cargo, arguments, manifest, config, packages)
}

fn prepare_config(role: Role, mixed: bool, offline: bool) -> Result<PathBuf, Box<dyn Error>> {
    let cache = cache_directory()?.join(match (role, mixed) {
        (Role::Host, _) => "host/tokio",
        (Role::Guest, false) => "guest/tokio",
        (Role::Guest, true) => "mixed/guest/tokio",
    });
    let cache_parent = cache.parent().ok_or("patch cache has no parent")?;
    fs::create_dir_all(cache_parent)?;
    let lock = File::create(cache_parent.join("lock"))?;
    lock.lock()?;
    if role == Role::Guest && mixed {
        telekio_build::prepare_mixed_guest_patch(&cache, offline)?;
    } else {
        telekio_build::prepare_patch(&cache, role, offline)?;
    }
    let config = write_config(&cache)?;
    drop(lock);
    Ok(config)
}

fn cargo_status(
    cargo: &OsStr,
    arguments: &[OsString],
    config: Option<&Path>,
) -> Result<process::ExitStatus, Box<dyn Error>> {
    let mut arguments = arguments.to_vec();
    let mut command = Command::new(cargo);
    if arguments
        .first()
        .and_then(|argument| argument.to_str())
        .is_some_and(|argument| argument.starts_with('+'))
    {
        command.arg(arguments.remove(0));
    }
    if let Some(config) = config {
        let split = arguments
            .iter()
            .position(|argument| argument == "--")
            .unwrap_or(arguments.len());
        let mut cargo = Vec::new();
        let mut configs = Vec::new();
        let mut index = 0;
        while index < split {
            let argument = arguments[index].to_string_lossy();
            if argument == "--config" {
                if let Some(value) = arguments.get(index + 1) {
                    configs.extend([arguments[index].clone(), value.clone()]);
                }
                index += 2;
            } else if argument.starts_with("--config=") {
                configs.push(arguments[index].clone());
                index += 1;
            } else {
                cargo.push(arguments[index].clone());
                index += 1;
            }
        }
        cargo.extend(configs);
        cargo.extend([OsString::from("--config"), config.as_os_str().to_owned()]);
        cargo.extend_from_slice(&arguments[split..]);
        arguments = cargo;
    }
    Ok(command.args(arguments).status()?)
}

impl ProjectInfo {
    fn roles(&self) -> Vec<Role> {
        let mut roles = Vec::new();
        for role in self.packages.iter().map(|package| package.role) {
            if !roles.contains(&role) {
                roles.push(role);
            }
        }
        roles
    }

    fn package_names(&self) -> Vec<String> {
        self.packages
            .iter()
            .map(|package| package.name.clone())
            .collect()
    }

    fn groups(&self) -> (Vec<String>, Vec<String>) {
        let mut host = Vec::new();
        let mut guest = Vec::new();
        for package in &self.packages {
            match package.role {
                Role::Host => host.push(package.name.clone()),
                Role::Guest => guest.push(package.name.clone()),
            }
        }
        (host, guest)
    }
}

fn offline(arguments: &[OsString]) -> bool {
    arguments
        .iter()
        .any(|argument| matches!(argument.to_str(), Some("--offline" | "--frozen")))
}

fn expand_alias(cargo: &OsStr, arguments: &[OsString]) -> Result<Vec<OsString>, Box<dyn Error>> {
    let mut expanded = arguments.to_vec();
    for _ in 0..16 {
        if operation(&expanded).is_some() {
            return Ok(expanded);
        }
        let output = Command::new(cargo)
            .args(global_options(&expanded))
            .args(["--color", "never", "--list"])
            .output()?;
        if !output.status.success() {
            return Ok(expanded);
        }
        let aliases = String::from_utf8(output.stdout)?;
        let Some((index, target)) = expanded.iter().enumerate().find_map(|(index, argument)| {
            let name = argument.to_str()?;
            aliases.lines().find_map(|line| {
                let (alias, target) = line.split_once(" alias: ")?;
                (alias.trim() == name).then_some((index, target))
            })
        }) else {
            return Ok(expanded);
        };
        if target.starts_with('!') {
            return Err("Cargo shell aliases cannot determine a Telekio artifact role; use the direct Cargo command".into());
        }
        expanded.splice(index..=index, target.split_whitespace().map(OsString::from));
    }
    Err("Cargo alias expansion is recursive".into())
}

fn project_info(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
) -> Result<ProjectInfo, Box<dyn Error>> {
    let output = Command::new(cargo)
        .args(global_options(arguments))
        .args(["metadata", "--format-version", "1", "--no-deps"])
        .arg("--manifest-path")
        .arg(manifest)
        .output()?;
    if !output.status.success() {
        return Err(format!(
            "Cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )
        .into());
    }
    let metadata: serde_json::Value = serde_json::from_slice(&output.stdout)?;
    let packages = metadata["packages"]
        .as_array()
        .ok_or("Cargo metadata has no packages")?;
    let (selected, workspace_selection) = selected_packages(&metadata, arguments, packages)?;
    let mut info = Vec::new();
    for id in selected {
        let package = packages
            .iter()
            .find(|package| package["id"].as_str() == Some(id))
            .ok_or("selected Cargo package was not found")?;
        let name = package["name"]
            .as_str()
            .ok_or("selected Cargo package has no name")?
            .to_owned();
        info.push(PackageInfo {
            name,
            role: package_role(package),
        });
    }
    let workspace_roles = metadata["workspace_members"]
        .as_array()
        .ok_or("Cargo metadata has no workspace members")?
        .iter()
        .filter_map(serde_json::Value::as_str)
        .filter_map(|id| {
            packages
                .iter()
                .find(|package| package["id"].as_str() == Some(id))
        })
        .map(package_role)
        .collect::<Vec<_>>();
    Ok(ProjectInfo {
        packages: info,
        workspace_selection,
        workspace_mixed: workspace_roles.contains(&Role::Host)
            && workspace_roles.contains(&Role::Guest),
    })
}

fn package_role(package: &serde_json::Value) -> Role {
    let mut guest = false;
    for dependency in package["dependencies"]
        .as_array()
        .into_iter()
        .flatten()
        .filter(|dependency| dependency["kind"].is_null())
    {
        let name = dependency["name"].as_str();
        let rename = dependency["rename"].as_str();
        if name == Some("telekio-host") || matches!(rename, Some("telekio-host" | "telekio_host")) {
            return Role::Host;
        }
        if name == Some("telekio") {
            guest = true;
        }
    }
    if guest { Role::Guest } else { Role::Host }
}

fn patch_selected(
    cargo: &OsStr,
    arguments: &[OsString],
    manifest: &Path,
    config: &Path,
    selected: &[String],
) -> Result<PatchState, Box<dyn Error>> {
    let output = Command::new(cargo)
        .args(global_options(arguments))
        .arg("--config")
        .arg(config)
        .args(["metadata", "--format-version", "1"])
        .args(metadata_options(arguments))
        .arg("--manifest-path")
        .arg(manifest)
        .output()?;
    if !output.status.success() {
        return Err(format!(
            "patched Cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )
        .into());
    }
    let metadata: serde_json::Value = serde_json::from_slice(&output.stdout)?;
    let packages = metadata["packages"]
        .as_array()
        .ok_or("Cargo metadata has no packages")?;
    let members = metadata["workspace_members"]
        .as_array()
        .ok_or("Cargo metadata has no workspace members")?;
    let ids = packages
        .iter()
        .filter(|package| {
            package["id"]
                .as_str()
                .is_some_and(|id| members.iter().any(|member| member.as_str() == Some(id)))
                && package["name"]
                    .as_str()
                    .is_some_and(|name| selected.iter().any(|selected| selected == name))
        })
        .filter_map(|package| package["id"].as_str())
        .collect::<Vec<_>>();
    let reachable = reachable_packages(&metadata, &ids)?;
    let expected = fs::canonicalize(
        config
            .parent()
            .ok_or("Telekio config has no parent")?
            .join("tokio/Cargo.toml"),
    )?;
    let mut selected_patch = false;
    for package in packages.iter().filter(|package| {
        package["id"]
            .as_str()
            .is_some_and(|id| reachable.contains(&id))
            && package["name"].as_str() == Some("tokio")
    }) {
        let path = package["manifest_path"]
            .as_str()
            .and_then(|path| fs::canonicalize(path).ok());
        if path.as_ref() == Some(&expected) {
            selected_patch = true;
        } else if crates_io(package) || generated_patch(package) {
            return Err("generated Tokio patch was not selected; run `telekio cargo update -p tokio`, or `cargo update -p tokio` after `telekio init`, then adjust incompatible Tokio version requirements".into());
        }
    }
    Ok(if selected_patch {
        PatchState::Selected
    } else {
        PatchState::Unused
    })
}

fn selected_packages<'a>(
    metadata: &'a serde_json::Value,
    arguments: &[OsString],
    packages: &'a [serde_json::Value],
) -> Result<(Vec<&'a str>, bool), Box<dyn Error>> {
    let operation = operation(arguments);
    let workspace = has_option(arguments, "--workspace") || has_option(arguments, "--all");
    let requested = option_values(arguments, &["-p", "--package"]);
    let members = metadata[if workspace {
        "workspace_members"
    } else {
        "workspace_default_members"
    }]
    .as_array()
    .ok_or("Cargo metadata has no workspace members")?;
    let member_ids = members
        .iter()
        .filter_map(serde_json::Value::as_str)
        .collect::<Vec<_>>();
    let mut names = requested
        .iter()
        .filter_map(|value| value.to_str())
        .map(|value| value.split_once('@').map_or(value, |(name, _)| name))
        .collect::<Vec<_>>();
    names.sort_unstable();
    names.dedup();
    let requested_ids = packages
        .iter()
        .filter(|package| {
            package["id"]
                .as_str()
                .is_some_and(|id| member_ids.contains(&id))
                && package["name"]
                    .as_str()
                    .is_some_and(|name| names.contains(&name))
        })
        .filter_map(|package| package["id"].as_str())
        .collect::<Vec<_>>();
    let selects_workspace = operation.is_some_and(package_selects_workspace)
        && (requested.is_empty() || requested_ids.len() == names.len());
    let mut selected = if workspace || requested.is_empty() || !selects_workspace {
        member_ids
    } else {
        requested_ids
    };
    let excluded = option_values(arguments, &["--exclude"]);
    selected.retain(|id| {
        packages
            .iter()
            .find(|package| package["id"].as_str() == Some(id))
            .and_then(|package| package["name"].as_str())
            .is_none_or(|name| !excluded.iter().any(|excluded| *excluded == name))
    });
    if selected.is_empty() {
        return Err("Cargo package selection matched no packages".into());
    }
    Ok((selected, selects_workspace))
}

fn crates_io(package: &serde_json::Value) -> bool {
    package["source"]
        .as_str()
        .is_some_and(|source| source.contains("crates.io-index"))
}

fn generated_patch(package: &serde_json::Value) -> bool {
    package["manifest_path"]
        .as_str()
        .and_then(|manifest| fs::read_to_string(manifest).ok())
        .is_some_and(|manifest| manifest.lines().any(|line| line.contains(GENERATED)))
}

fn reachable_packages<'a>(
    metadata: &'a serde_json::Value,
    selected: &[&'a str],
) -> Result<Vec<&'a str>, Box<dyn Error>> {
    let nodes = metadata["resolve"]["nodes"]
        .as_array()
        .ok_or("Cargo metadata has no resolve nodes")?;
    let mut reachable = selected.to_vec();
    let mut index = 0;
    while index < reachable.len() {
        if let Some(node) = nodes
            .iter()
            .find(|node| node["id"].as_str() == Some(reachable[index]))
            && let Some(dependencies) = node["dependencies"].as_array()
        {
            for dependency in dependencies.iter().filter_map(serde_json::Value::as_str) {
                if !reachable.contains(&dependency) {
                    reachable.push(dependency);
                }
            }
        }
        index += 1;
    }
    Ok(reachable)
}

fn project_manifest(
    cargo: &OsStr,
    arguments: &[OsString],
) -> Result<Option<PathBuf>, Box<dyn Error>> {
    if operation(arguments) == Some("install") && !has_option(arguments, "--path") {
        return Ok(None);
    }
    let mut command = Command::new(cargo);
    command
        .args(global_options(arguments))
        .args(["locate-project", "--message-format", "plain"]);
    if let Some(path) = option(arguments, "--manifest-path") {
        command.arg("--manifest-path").arg(path);
    } else if let Some(path) = option(arguments, "--path") {
        command
            .arg("--manifest-path")
            .arg(Path::new(path).join("Cargo.toml"));
    }
    let output = command.output()?;
    if !output.status.success() {
        return Ok(None);
    }
    let path = String::from_utf8(output.stdout)?;
    Ok(Some(PathBuf::from(path.trim())))
}

fn metadata_options(arguments: &[OsString]) -> Vec<OsString> {
    let mut options = Vec::new();
    let mut index = 0;
    while index < arguments.len() && arguments[index] != "--" {
        let Some(argument) = arguments[index].to_str() else {
            index += 1;
            continue;
        };
        if matches!(argument, "--features" | "-F" | "--target") {
            if let Some(value) = arguments.get(index + 1) {
                options.push(OsString::from(if argument == "--target" {
                    "--filter-platform"
                } else {
                    argument
                }));
                options.push(value.clone());
            }
            index += 2;
            continue;
        }
        if argument.starts_with("--features=")
            || (argument.starts_with("-F") && argument.len() > "-F".len())
            || matches!(
                argument,
                "--all-features" | "--no-default-features" | "--locked" | "--frozen" | "--offline"
            )
        {
            options.push(arguments[index].clone());
        } else if let Some(target) = argument.strip_prefix("--target=") {
            options.push(OsString::from(format!("--filter-platform={target}")));
        }
        index += 1;
    }
    options
}

fn global_options(arguments: &[OsString]) -> Vec<&OsStr> {
    let mut options = Vec::new();
    let mut index = 0;
    while index < arguments.len() && arguments[index] != "--" {
        let Some(argument) = arguments[index].to_str() else {
            index += 1;
            continue;
        };
        if argument.starts_with('+') && index == 0 {
            options.push(arguments[index].as_os_str());
            index += 1;
            continue;
        }
        if argument == "--config" || argument == "-C" {
            if let Some(value) = arguments.get(index + 1) {
                options.extend([arguments[index].as_os_str(), value.as_os_str()]);
            }
            index += 2;
            continue;
        }
        if argument.starts_with("--config=") || argument.starts_with("-C=") {
            options.push(arguments[index].as_os_str());
            index += 1;
            continue;
        }
        index += 1;
    }
    options
}

fn operation(arguments: &[OsString]) -> Option<&str> {
    const COMMANDS: &[&str] = &[
        "add",
        "bench",
        "build",
        "check",
        "clean",
        "clippy",
        "doc",
        "fetch",
        "fix",
        "fmt",
        "generate-lockfile",
        "help",
        "info",
        "init",
        "install",
        "locate-project",
        "login",
        "logout",
        "metadata",
        "new",
        "owner",
        "package",
        "publish",
        "remove",
        "report",
        "run",
        "rustc",
        "rustdoc",
        "search",
        "test",
        "tree",
        "uninstall",
        "update",
        "vendor",
        "yank",
    ];
    arguments
        .iter()
        .take_while(|argument| *argument != "--")
        .filter_map(|argument| argument.to_str())
        .find(|argument| COMMANDS.contains(argument))
}

fn command_kind(operation: &str) -> CommandKind {
    match operation {
        "bench" | "build" | "check" | "clippy" | "doc" | "fix" | "package" | "publish" | "test"
        | "tree" => CommandKind::Packages,
        "fetch" | "generate-lockfile" | "update" => CommandKind::Workspace,
        "add" | "install" | "remove" | "run" | "rustc" | "rustdoc" => CommandKind::Single,
        "metadata" | "vendor" => CommandKind::Output,
        "clean" | "fmt" | "help" | "info" | "init" | "locate-project" | "login" | "logout"
        | "new" | "owner" | "report" | "search" | "uninstall" | "yank" => CommandKind::Plain,
        _ => CommandKind::Output,
    }
}

fn package_selects_workspace(operation: &str) -> bool {
    matches!(
        operation,
        "add"
            | "bench"
            | "build"
            | "check"
            | "clean"
            | "clippy"
            | "doc"
            | "fix"
            | "package"
            | "publish"
            | "remove"
            | "run"
            | "rustc"
            | "rustdoc"
            | "test"
            | "tree"
    )
}

fn package_arguments(arguments: &[OsString], packages: &[String]) -> Vec<OsString> {
    let split = arguments
        .iter()
        .position(|argument| argument == "--")
        .unwrap_or(arguments.len());
    let mut selected = Vec::new();
    let mut index = 0;
    while index < split {
        let argument = arguments[index].to_string_lossy();
        if matches!(argument.as_ref(), "--workspace" | "--all") {
            index += 1;
        } else if matches!(argument.as_ref(), "-p" | "--package" | "--exclude") {
            index += 2;
        } else if argument.starts_with("--package=")
            || argument.starts_with("--exclude=")
            || (argument.starts_with("-p") && argument.len() > 2)
        {
            index += 1;
        } else {
            selected.push(arguments[index].clone());
            index += 1;
        }
    }
    for package in packages {
        selected.extend([OsString::from("--package"), OsString::from(package)]);
    }
    selected.extend_from_slice(&arguments[split..]);
    selected
}

fn option_values<'a>(arguments: &'a [OsString], names: &[&str]) -> Vec<&'a OsStr> {
    let mut values = Vec::new();
    for (index, argument) in arguments
        .iter()
        .take_while(|argument| *argument != "--")
        .enumerate()
    {
        let Some(argument) = argument.to_str() else {
            continue;
        };
        for name in names {
            if argument == *name {
                if let Some(value) = arguments.get(index + 1) {
                    values.push(value.as_os_str());
                }
            } else if *name == "-p" && argument.starts_with("-p") && argument.len() > "-p".len() {
                values.push(OsStr::new(&argument["-p".len()..]));
            } else if let Some(value) = argument.strip_prefix(&format!("{name}=")) {
                values.push(OsStr::new(value));
            }
        }
    }
    values
}

fn has_option(arguments: &[OsString], name: &str) -> bool {
    arguments
        .iter()
        .take_while(|argument| *argument != "--")
        .any(|argument| {
            argument.to_str().is_some_and(|argument| {
                argument == name || argument.starts_with(&format!("{name}="))
            })
        })
}

fn option<'a>(arguments: &'a [OsString], name: &str) -> Option<&'a OsStr> {
    for (index, argument) in arguments
        .iter()
        .take_while(|argument| *argument != "--")
        .enumerate()
    {
        let Some(argument) = argument.to_str() else {
            continue;
        };
        if argument == name {
            return arguments.get(index + 1).map(OsString::as_os_str);
        }
        if let Some(value) = argument.strip_prefix(&format!("{name}=")) {
            return Some(OsStr::new(value));
        }
    }
    None
}

fn cache_directory() -> Result<PathBuf, Box<dyn Error>> {
    let directory = env::temp_dir().join("telekio");
    fs::create_dir_all(&directory)?;
    Ok(directory)
}

fn write_config(patch: &Path) -> Result<PathBuf, Box<dyn Error>> {
    let path = patch
        .parent()
        .ok_or("patch directory has no parent")?
        .join("config.toml");
    let mut dependency = toml::Table::new();
    dependency.insert(
        "path".to_owned(),
        toml::Value::String(
            patch
                .to_str()
                .ok_or("patch path is not valid Unicode")?
                .to_owned(),
        ),
    );
    let config = toml::Value::Table(toml::Table::from_iter([(
        "patch".to_owned(),
        toml::Value::Table(toml::Table::from_iter([(
            "crates-io".to_owned(),
            toml::Value::Table(toml::Table::from_iter([(
                "tokio".to_owned(),
                toml::Value::Table(dependency),
            )])),
        )])),
    )]));
    fs::write(&path, toml::to_string(&config)?)?;
    Ok(path)
}

fn exit(status: process::ExitStatus) -> Result<(), Box<dyn Error>> {
    process::exit(status.code().unwrap_or(1));
}
