#[path = "io.rs"]
mod host_io;
#[path = "signal.rs"]
mod host_signal;
mod task;

use std::{
    any::Any,
    cell::{Cell, UnsafeCell},
    collections::HashMap,
    ffi::c_void,
    io,
    panic::{AssertUnwindSafe, catch_unwind, resume_unwind},
    pin::Pin,
    sync::{Arc, Mutex, OnceLock, RwLock, Weak},
    task::{Context as TaskContext, Poll as RustPoll},
    thread::ThreadId,
    time::Duration,
};

use telekio::{
    AttachResult, Blocking, BuildResult, CallResult, Callback, ClockSample, DurationParts, Flavor,
    GuestCall, InstantOffset, Metric, MetricResult, NameResult, OperationPoll, OwnedBytes, Poll,
    RawAttachment, RawHandle, RawRuntime, RuntimeApi, RuntimeConfig, Shutdown, Status,
    StringCallback, Timer, TimerResult, Waker, WorkerCallback,
};

pub struct Runtime {
    runtime: Arc<tokio::runtime::Runtime>,
    flavor: Flavor,
}

pub struct Owner {
    runtime: Arc<tokio::runtime::Runtime>,
    handle: Arc<HandleContext>,
}

/// Plugin entry generated by `telekio::plugin!()`.
pub type Attach = unsafe extern "C" fn(RawHandle) -> AttachResult;

/// One loaded plugin's connection to a Telekio owner.
#[must_use = "the attachment must be shut down before unloading its plugin"]
pub struct Attachment {
    raw: Option<RawAttachment>,
    owner: Arc<OwnerState>,
}

struct GuestCallState<F, R> {
    call: Option<F>,
    output: Option<R>,
}

struct RuntimeOwner {
    id: OnceLock<u64>,
    owner: Weak<OwnerState>,
    kind: RwLock<RuntimeKind>,
}

enum RuntimeKind {
    Runtime(Option<tokio::runtime::Runtime>),
    Local(Arc<LocalSlot>),
    Closed,
}

struct HandleContext {
    handle: tokio::runtime::Handle,
    owner: Arc<OwnerState>,
    flavor: Flavor,
    local: Option<Arc<LocalSlot>>,
    io_enabled: bool,
    worker_observer: Mutex<Option<WorkerObserver>>,
}

struct LocalSlot {
    thread: ThreadId,
    runtime: UnsafeCell<Option<tokio::runtime::LocalRuntime>>,
}

struct OwnerState {
    state: Mutex<OwnerStatus>,
    notify: tokio::sync::Notify,
    shutdown: tokio::sync::Mutex<()>,
}

struct OwnerStatus {
    accepting: bool,
    handles: HashMap<usize, HandleRecord>,
    tasks: HashMap<u64, TaskRecord>,
    activities: HashMap<u64, Option<std::task::Waker>>,
    runtimes: HashMap<u64, Arc<RuntimeOwner>>,
    resources: HashMap<u64, Arc<dyn OwnerResource>>,
    next_id: u64,
}

struct HandleRecord {
    context: Arc<HandleContext>,
    references: usize,
}

struct TaskRecord {
    handle: Option<tokio::task::AbortHandle>,
}

trait OwnerResource: Send + Sync {
    fn close(&self);
    fn is_closed(&self) -> bool;
}

struct HostResource<T: Send> {
    owner: Weak<OwnerState>,
    id: OnceLock<u64>,
    value: Mutex<Option<T>>,
    waker: Mutex<Option<std::task::Waker>>,
}

struct Activity {
    owner: Arc<OwnerState>,
    id: u64,
    _context: OwnerContext,
}

struct WorkerObserver {
    handle: tokio::runtime::Handle,
    id: Option<u64>,
}

struct WorkerCallbackOwner(WorkerCallback);

unsafe impl Send for WorkerCallbackOwner {}
unsafe impl Sync for WorkerCallbackOwner {}

struct OwnerContext {
    previous: *const OwnerState,
}

struct TaskCleanup {
    owner: Arc<OwnerState>,
    id: u64,
}

struct CallbackCleanup {
    owner: Arc<OwnerState>,
    id: u64,
}

struct TimeTimer {
    sleep: Pin<Box<tokio::time::Sleep>>,
}

struct CallbackOwner(Callback);
struct StringCallbackOwner(StringCallback);

unsafe impl Send for CallbackOwner {}
unsafe impl Sync for CallbackOwner {}
unsafe impl Send for StringCallbackOwner {}
unsafe impl Sync for StringCallbackOwner {}

// LocalRuntime stays in its originating thread. HandleContext only shares the slot's
// address and checks that thread before every access to the contained runtime.
unsafe impl Send for LocalSlot {}
unsafe impl Sync for LocalSlot {}

thread_local! {
    static ACTIVE_OWNER: Cell<*const OwnerState> = const { Cell::new(std::ptr::null()) };
}

static CLOCK_ORIGIN: OnceLock<std::time::Instant> = OnceLock::new();

static RUNTIME_API: RuntimeApi = RuntimeApi {
    runtime_block_on: task::runtime_block_on,
    handle_block_on: task::handle_block_on,
    retain_handle,
    release_handle,
    release_runtime,
    detach,
    spawn: task::spawn,
    spawn_local: task::spawn_local,
    spawn_blocking: task::spawn_blocking,
    block_in_place,
    build,
    clock,
    pause,
    resume,
    advance,
    timer,
    register_io: host_io::register,
    signal: host_signal::signal,
    reap_process,
    shutdown,
    defer,
    metric,
    flavor,
    id,
    name,
    observe_workers,
};

impl Runtime {
    pub fn new() -> io::Result<Self> {
        tokio::runtime::Runtime::new().map(Self::from_tokio)
    }

    pub fn from_tokio(runtime: tokio::runtime::Runtime) -> Self {
        let flavor = match runtime.handle().runtime_flavor() {
            tokio::runtime::RuntimeFlavor::CurrentThread => Flavor::CurrentThread,
            tokio::runtime::RuntimeFlavor::MultiThread => Flavor::MultiThread,
            _ => unreachable!("unsupported Tokio runtime flavor"),
        };
        Self {
            runtime: Arc::new(runtime),
            flavor,
        }
    }

    pub fn owner(&self) -> Owner {
        Owner {
            runtime: Arc::clone(&self.runtime),
            handle: handle_context(
                self.runtime.handle().clone(),
                owner_state(),
                None,
                true,
                self.flavor,
            ),
        }
    }

    pub fn tokio(&self) -> &tokio::runtime::Runtime {
        &self.runtime
    }
}

impl Owner {
    pub fn runtime(&self) -> telekio::Handle {
        unsafe { telekio::Handle::from_abi(raw_handle(Arc::clone(&self.handle))) }
    }

    pub async fn shutdown(&self) -> io::Result<()> {
        if ACTIVE_OWNER.get() == Arc::as_ptr(&self.handle.owner) {
            return Err(io::Error::other(
                "owner shutdown cannot run inside one of its guest callbacks",
            ));
        }
        let _shutdown = self.handle.owner.shutdown.lock().await;
        shutdown_owner(&self.handle.owner, self.runtime.handle()).await
    }

    /// # Safety
    ///
    /// `attach` must belong to a loaded plugin and remain callable until this
    /// owner's attachment is detached.
    pub unsafe fn attach(&self, attach: Attach) -> io::Result<Attachment> {
        let result = unsafe { attach(self.runtime().into_abi()) };
        result.call.into_io_result()?;
        Ok(Attachment {
            raw: Some(result.attachment),
            owner: Arc::clone(&self.handle.owner),
        })
    }

    /// Stops this owner and detaches its plugin before the library is unloaded.
    pub async fn detach(&self, attachment: &mut Attachment) -> io::Result<()> {
        if !Arc::ptr_eq(&self.handle.owner, &attachment.owner) {
            return Err(io::Error::other(
                "Telekio attachment belongs to another owner",
            ));
        }
        self.shutdown().await?;
        attachment.detach()
    }
}

impl Attachment {
    /// Runs a plugin entry inside its attached Tokio runtime context.
    pub fn enter<F: FnOnce() -> R, R>(&self, call: F) -> R {
        let raw = self.raw.as_ref().expect("Telekio attachment is detached");
        let activity = self
            .owner
            .activity()
            .unwrap_or_else(|error| panic!("{error}"));
        let mut state = GuestCallState {
            call: Some(call),
            output: None,
        };
        let call = unsafe { GuestCall::from_raw((&raw mut state).cast(), run_guest_call::<F, R>) };
        unsafe { raw.enter(call) }.resume("failed to enter Telekio guest runtime");
        drop(activity);
        state.output.take().expect("Telekio guest call did not run")
    }

    fn detach(&mut self) -> io::Result<()> {
        let raw = self
            .raw
            .as_ref()
            .ok_or_else(|| io::Error::other("Telekio attachment is already detached"))?;
        unsafe { raw.detach() }.into_io_result()?;
        self.raw = None;
        Ok(())
    }
}

unsafe extern "C" fn run_guest_call<F: FnOnce() -> R, R>(data: *mut c_void) -> CallResult {
    let state = unsafe { &mut *data.cast::<GuestCallState<F, R>>() };
    match catch_unwind(AssertUnwindSafe(|| {
        let call = state.call.take().expect("Telekio guest call ran twice");
        state.output = Some(call());
    })) {
        Ok(()) => CallResult::ok(),
        Err(payload) => CallResult::panicked(&*payload),
    }
}

fn owner_state() -> Arc<OwnerState> {
    Arc::new(OwnerState {
        state: Mutex::new(OwnerStatus {
            accepting: true,
            handles: HashMap::new(),
            tasks: HashMap::new(),
            activities: HashMap::new(),
            runtimes: HashMap::new(),
            resources: HashMap::new(),
            next_id: 1,
        }),
        notify: tokio::sync::Notify::new(),
        shutdown: tokio::sync::Mutex::new(()),
    })
}

impl OwnerState {
    fn is_accepting(&self) -> bool {
        self.state.lock().unwrap().accepting
    }

    fn accepting(&self) -> Result<(), String> {
        self.is_accepting()
            .then_some(())
            .ok_or_else(|| "Tokio owner is shutting down".to_owned())
    }

    fn callback(self: &Arc<Self>, waker: std::task::Waker) -> Option<CallbackCleanup> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return None;
        }
        let id = state.next_id;
        state.next_id += 1;
        state.activities.insert(id, Some(waker));
        Some(CallbackCleanup {
            owner: Arc::clone(self),
            id,
        })
    }

    fn activity(self: &Arc<Self>) -> Result<Activity, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.activities.insert(id, None);
        Ok(Activity {
            owner: Arc::clone(self),
            id,
            _context: OwnerContext::enter(self),
        })
    }

    fn update_activity_waker(&self, id: u64, waker: &std::task::Waker) -> bool {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return false;
        }
        if let Some(slot) = state.activities.get_mut(&id) {
            *slot = Some(waker.clone());
        }
        true
    }

    fn wake_activities(&self) {
        let wakers = self
            .state
            .lock()
            .unwrap()
            .activities
            .values()
            .filter_map(Clone::clone)
            .collect::<Vec<_>>();
        for waker in wakers {
            waker.wake();
        }
    }

    fn export_handle(&self, context: Arc<HandleContext>) {
        let key = Arc::as_ptr(&context) as usize;
        let mut state = self.state.lock().unwrap();
        let handle = state.handles.entry(key).or_insert(HandleRecord {
            context,
            references: 0,
        });
        handle.references += 1;
    }

    fn retain_handle(&self, context: *const HandleContext) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        let handle = state
            .handles
            .get_mut(&(context as usize))
            .ok_or_else(|| "Tokio handle is detached".to_owned())?;
        handle.references += 1;
        Ok(())
    }

    fn release_handle(&self, context: *const HandleContext) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        let key = context as usize;
        let handle = state
            .handles
            .get_mut(&key)
            .ok_or_else(|| "Tokio handle is detached".to_owned())?;
        handle.references = handle
            .references
            .checked_sub(1)
            .ok_or_else(|| "Tokio handle reference count is empty".to_owned())?;
        let _handle = if handle.references == 0 {
            state.handles.remove(&key)
        } else {
            None
        };
        Ok(())
    }

    fn reserve_task(&self) -> Result<u64, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.tasks.insert(id, TaskRecord { handle: None });
        Ok(id)
    }

    fn register_task(&self, id: u64, handle: tokio::task::AbortHandle) {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            handle.abort();
        }
        if let Some(task) = state.tasks.get_mut(&id) {
            task.handle = Some(handle);
        }
    }

    fn finish_task(&self, id: u64) {
        self.state.lock().unwrap().tasks.remove(&id);
        self.notify.notify_waiters();
    }

    fn register_runtime(&self, runtime: Arc<RuntimeOwner>) -> Result<u64, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.runtimes.insert(id, runtime);
        Ok(id)
    }

    fn unregister_runtime(&self, id: u64) -> Option<Arc<RuntimeOwner>> {
        self.state.lock().unwrap().runtimes.remove(&id)
    }

    fn register_resource(&self, resource: Arc<dyn OwnerResource>) -> Result<u64, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.resources.insert(id, resource);
        Ok(id)
    }

    fn unregister_resource(&self, id: u64) -> Option<Arc<dyn OwnerResource>> {
        self.state.lock().unwrap().resources.remove(&id)
    }

    fn begin_shutdown(
        &self,
    ) -> (
        Vec<tokio::task::AbortHandle>,
        Vec<Arc<dyn OwnerResource>>,
        Vec<std::task::Waker>,
    ) {
        let mut state = self.state.lock().unwrap();
        state.accepting = false;
        let tasks = state
            .tasks
            .values()
            .filter_map(|task| task.handle.clone())
            .collect();
        let resources = state.resources.values().cloned().collect();
        let activities = state.activities.values().filter_map(Clone::clone).collect();
        (tasks, resources, activities)
    }

    async fn wait_idle(&self) {
        loop {
            let notified = self.notify.notified();
            let idle = {
                let state = self.state.lock().unwrap();
                state.tasks.is_empty() && state.activities.is_empty()
            };
            if idle {
                return;
            }
            notified.await;
        }
    }

    fn runtimes(&self) -> io::Result<Vec<Arc<RuntimeOwner>>> {
        let state = self.state.lock().unwrap();
        if state.runtimes.values().any(|runtime| runtime.local_open()) {
            return Err(io::Error::other(
                "LocalRuntime must be dropped on its originating thread before owner shutdown",
            ));
        }
        Ok(state.runtimes.values().cloned().collect())
    }

    fn detach(&self) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        if state.accepting || !state.tasks.is_empty() || !state.activities.is_empty() {
            return Err("Tokio owner must shut down before detaching".to_owned());
        }
        if state.runtimes.values().any(|runtime| !runtime.is_closed())
            || state
                .resources
                .values()
                .any(|resource| !resource.is_closed())
        {
            return Err("Tokio owner has live runtime resources".to_owned());
        }
        debug_assert!(
            state
                .handles
                .iter()
                .all(|(key, handle)| *key == Arc::as_ptr(&handle.context) as usize)
        );
        state.handles.clear();
        state.runtimes.clear();
        state.resources.clear();
        Ok(())
    }
}

impl OwnerContext {
    fn enter(owner: &Arc<OwnerState>) -> Self {
        Self {
            previous: ACTIVE_OWNER.replace(Arc::as_ptr(owner)),
        }
    }
}

impl Drop for OwnerContext {
    fn drop(&mut self) {
        ACTIVE_OWNER.set(self.previous);
    }
}

impl Drop for Activity {
    fn drop(&mut self) {
        self.owner.state.lock().unwrap().activities.remove(&self.id);
        self.owner.notify.notify_waiters();
    }
}

impl Drop for TaskCleanup {
    fn drop(&mut self) {
        self.owner.finish_task(self.id);
    }
}

impl Drop for CallbackCleanup {
    fn drop(&mut self) {
        self.owner.state.lock().unwrap().activities.remove(&self.id);
        self.owner.notify.notify_waiters();
    }
}

impl<T: Send + 'static> OwnerResource for HostResource<T> {
    fn close(&self) {
        self.value.lock().unwrap().take();
        if let Some(waker) = self.waker.lock().unwrap().take() {
            waker.wake();
        }
    }

    fn is_closed(&self) -> bool {
        self.value.lock().unwrap().is_none()
    }
}

impl<T: Send + 'static> HostResource<T> {
    fn new(owner: &Arc<OwnerState>, value: T) -> Result<Arc<Self>, String> {
        let resource = Arc::new(Self {
            owner: Arc::downgrade(owner),
            id: OnceLock::new(),
            value: Mutex::new(Some(value)),
            waker: Mutex::new(None),
        });
        let id = owner.register_resource(Arc::clone(&resource) as Arc<dyn OwnerResource>)?;
        resource.id.set(id).unwrap();
        Ok(resource)
    }

    fn update_waker(&self, waker: &Waker) {
        let value = self.value.lock().unwrap();
        if value.is_some() {
            *self.waker.lock().unwrap() = Some(unsafe { waker.clone_rust_waker() });
        }
    }

    fn with<R>(&self, call: impl FnOnce(&T) -> R) -> Result<R, String> {
        self.value
            .lock()
            .unwrap()
            .as_ref()
            .map(call)
            .ok_or_else(|| "Tokio owner has shut down".to_owned())
    }

    fn with_mut<R>(&self, call: impl FnOnce(&mut T) -> R) -> Result<R, String> {
        self.value
            .lock()
            .unwrap()
            .as_mut()
            .map(call)
            .ok_or_else(|| "Tokio owner has shut down".to_owned())
    }

    fn release(&self) {
        if let Some(owner) = self.owner.upgrade() {
            let _resource = owner.unregister_resource(*self.id.get().unwrap());
        }
    }
}

async fn shutdown_owner(
    owner: &Arc<OwnerState>,
    handle: &tokio::runtime::Handle,
) -> io::Result<()> {
    let (tasks, resources, activities) = owner.begin_shutdown();
    for task in tasks {
        task.abort();
    }
    for resource in resources {
        resource.close();
    }
    for activity in activities {
        activity.wake();
    }

    let runtimes = owner.runtimes()?;
    let close = handle.spawn_blocking(move || {
        for runtime in runtimes {
            runtime.close(Shutdown::Wait, Duration::ZERO)?;
        }
        Ok::<_, io::Error>(())
    });
    close.await.map_err(io::Error::other)??;
    owner.wait_idle().await;
    Ok(())
}

impl RuntimeOwner {
    fn is_closed(&self) -> bool {
        matches!(&*self.kind.read().unwrap(), RuntimeKind::Closed)
    }

    fn local_open(&self) -> bool {
        matches!(&*self.kind.read().unwrap(), RuntimeKind::Local(_))
    }

    fn close(&self, mode: Shutdown, duration: Duration) -> io::Result<()> {
        let mut kind = self.kind.write().unwrap();
        match &mut *kind {
            RuntimeKind::Runtime(runtime) => {
                let runtime = runtime.take();
                *kind = RuntimeKind::Closed;
                drop(kind);
                if let Some(runtime) = runtime {
                    shutdown_runtime(runtime, mode, duration);
                }
            }
            RuntimeKind::Local(local) => {
                let runtime = local.take().map_err(io::Error::other)?;
                *kind = RuntimeKind::Closed;
                drop(kind);
                if let Some(runtime) = runtime {
                    shutdown_local(runtime, mode, duration);
                }
            }
            RuntimeKind::Closed => {}
        }
        Ok(())
    }
}

impl LocalSlot {
    fn new(runtime: tokio::runtime::LocalRuntime) -> Self {
        Self {
            thread: std::thread::current().id(),
            runtime: UnsafeCell::new(Some(runtime)),
        }
    }

    fn with<R>(&self, call: impl FnOnce(&tokio::runtime::LocalRuntime) -> R) -> Result<R, String> {
        if std::thread::current().id() != self.thread {
            return Err("LocalRuntime was used from another thread".to_owned());
        }
        let runtime = unsafe { &*self.runtime.get() }
            .as_ref()
            .ok_or_else(|| "Tokio runtime has shut down".to_owned())?;
        Ok(call(runtime))
    }

    fn take(&self) -> Result<Option<tokio::runtime::LocalRuntime>, String> {
        if std::thread::current().id() != self.thread {
            return Err("LocalRuntime was used from another thread".to_owned());
        }
        Ok(unsafe { &mut *self.runtime.get() }.take())
    }
}

impl CallbackOwner {
    fn is_some(&self) -> bool {
        self.0.is_some()
    }

    fn call(&self) {
        let result = self.0.call();
        match result.status {
            Status::Ok => unsafe { result.payload.release() },
            Status::Panicked | Status::HostPanicked | Status::Error => {
                resume_unwind(Box::new(unsafe { result.payload.into_string() }));
            }
        }
    }
}

impl WorkerCallbackOwner {
    fn call(&self, worker: usize) -> CallResult {
        self.0.call(worker)
    }
}

impl Drop for WorkerObserver {
    fn drop(&mut self) {
        self.handle.telekio_remove_worker_observer(self.id);
    }
}

impl StringCallbackOwner {
    fn call(&self) -> String {
        let result = self.0.call();
        match result.status {
            Status::Ok => unsafe { result.payload.into_string() },
            Status::Panicked | Status::HostPanicked | Status::Error => {
                resume_unwind(Box::new(unsafe { result.payload.into_string() }));
            }
        }
    }
}

unsafe extern "C" fn retain_handle(context: *const c_void) -> CallResult {
    host_callback(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let owner = Arc::clone(&context.owner);
        owner
            .retain_handle(context)
            .unwrap_or_else(|error| panic!("{error}"));
    })
}

unsafe extern "C" fn release_handle(context: *const c_void) -> CallResult {
    host_callback(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let owner = Arc::clone(&context.owner);
        owner
            .release_handle(context)
            .unwrap_or_else(|error| panic!("{error}"));
    })
}

unsafe extern "C" fn release_runtime(owner: *mut c_void) -> CallResult {
    host_callback(|| {
        let runtime = unsafe { &*owner.cast::<RuntimeOwner>() };
        if let Some(owner) = runtime.owner.upgrade() {
            let _runtime = owner.unregister_runtime(*runtime.id.get().unwrap());
        }
    })
}

unsafe extern "C" fn detach(context: *const c_void) -> CallResult {
    match catch_unwind(AssertUnwindSafe(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        Arc::clone(&context.owner).detach()
    })) {
        Ok(Ok(())) => CallResult::ok(),
        Ok(Err(error)) => result(Status::Error, OwnedBytes::from_string(error)),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn defer(context: *const c_void, waker: *const Waker) -> CallResult {
    let context = unsafe { &*context.cast::<HandleContext>() };
    match catch_unwind(AssertUnwindSafe(|| {
        let waker = unsafe { (*waker).clone_rust_waker() };
        let Some(cleanup) = context.owner.callback(waker.clone()) else {
            waker.wake();
            return;
        };
        let wake = waker.clone();
        let task = context.handle.spawn(async move {
            tokio::task::yield_now().await;
            waker.wake();
            drop(cleanup);
        });
        if task.is_finished() {
            wake.wake();
        }
    })) {
        Ok(()) => result(Status::Ok, OwnedBytes::empty()),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn metric(
    context: *const c_void,
    metric: Metric,
    worker: usize,
    bucket: usize,
) -> MetricResult {
    match catch_unwind(AssertUnwindSafe(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        context.owner.accepting()?;
        let metrics = context.handle.metrics();
        #[cfg(not(target_has_atomic = "64"))]
        let _ = (worker, bucket);
        Ok::<_, String>(match metric {
            Metric::GlobalQueueDepth => metrics.global_queue_depth() as u64,
            Metric::NumWorkers => metrics.num_workers() as u64,
            Metric::NumBlockingThreads => metrics.num_blocking_threads() as u64,
            Metric::NumIdleBlockingThreads => metrics.num_idle_blocking_threads() as u64,
            Metric::WorkerLocalQueueDepth => metrics.worker_local_queue_depth(worker) as u64,
            Metric::BlockingQueueDepth => metrics.blocking_queue_depth() as u64,
            Metric::PollTimeHistogramEnabled => metrics.poll_time_histogram_enabled().into(),
            Metric::PollTimeHistogramNumBuckets => metrics.poll_time_histogram_num_buckets() as u64,
            Metric::PollTimeHistogramRangeStart => metrics
                .poll_time_histogram_bucket_range(bucket)
                .start
                .as_nanos() as u64,
            Metric::PollTimeHistogramRangeEnd => metrics
                .poll_time_histogram_bucket_range(bucket)
                .end
                .as_nanos() as u64,
            Metric::ScheduleLatencyHistogramEnabled => {
                metrics.schedule_latency_histogram_enabled().into()
            }
            Metric::ScheduleLatencyHistogramNumBuckets => {
                metrics.schedule_latency_histogram_num_buckets() as u64
            }
            Metric::ScheduleLatencyHistogramRangeStart => metrics
                .schedule_latency_histogram_bucket_range(bucket)
                .start
                .as_nanos() as u64,
            Metric::ScheduleLatencyHistogramRangeEnd => metrics
                .schedule_latency_histogram_bucket_range(bucket)
                .end
                .as_nanos() as u64,
            Metric::CurrentWorkerIndex => tokio::runtime::worker_index()
                .map(|worker| worker as u64 + 1)
                .unwrap_or_default(),
            Metric::WorkerTotalBusyDuration => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_total_busy_duration(worker).as_nanos() as u64
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerParkCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_park_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerParkUnparkCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_park_unpark_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::RemoteScheduleCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.remote_schedule_count()
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerNoopCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_noop_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerStealCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_steal_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerStealOperations => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_steal_operations(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerPollCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_poll_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerLocalScheduleCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_local_schedule_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerOverflowCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_overflow_count(worker)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::PollTimeHistogramBucketCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.poll_time_histogram_bucket_count(worker, bucket)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::WorkerMeanPollTime => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.worker_mean_poll_time(worker).as_nanos() as u64
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::ScheduleLatencyHistogramBucketCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.schedule_latency_histogram_bucket_count(worker, bucket)
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::IoDriverFdRegisteredCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.io_driver_fd_registered_count()
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::IoDriverFdDeregisteredCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.io_driver_fd_deregistered_count()
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
            Metric::IoDriverReadyCount => {
                #[cfg(target_has_atomic = "64")]
                {
                    metrics.io_driver_ready_count()
                }
                #[cfg(not(target_has_atomic = "64"))]
                {
                    0
                }
            }
        })
    })) {
        Ok(Ok(value)) => MetricResult {
            call: result(Status::Ok, OwnedBytes::empty()),
            value,
        },
        Ok(Err(error)) => MetricResult {
            call: result(Status::Error, OwnedBytes::from_string(error)),
            value: 0,
        },
        Err(payload) => MetricResult {
            call: host_panic(&*payload),
            value: 0,
        },
    }
}

unsafe extern "C" fn flavor(context: *const c_void) -> Flavor {
    unsafe { &*context.cast::<HandleContext>() }.flavor
}

unsafe extern "C" fn id(context: *const c_void) -> u64 {
    unsafe { &*context.cast::<HandleContext>() }
        .handle
        .id()
        .telekio_value()
}

unsafe extern "C" fn name(context: *const c_void) -> NameResult {
    match catch_unwind(AssertUnwindSafe(|| {
        unsafe { &*context.cast::<HandleContext>() }
            .handle
            .name()
            .map(str::to_owned)
    })) {
        Ok(Some(value)) => NameResult {
            call: CallResult::ok(),
            value: OwnedBytes::from_string(value),
            is_some: true,
        },
        Ok(None) => NameResult {
            call: CallResult::ok(),
            value: OwnedBytes::empty(),
            is_some: false,
        },
        Err(payload) => NameResult {
            call: host_panic(&*payload),
            value: OwnedBytes::empty(),
            is_some: false,
        },
    }
}

unsafe extern "C" fn observe_workers(
    context: *const c_void,
    callback: WorkerCallback,
) -> CallResult {
    match catch_unwind(AssertUnwindSafe(|| -> Result<(), String> {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let _activity = context.owner.activity()?;
        let mut observer = context.worker_observer.lock().unwrap();
        if observer.is_some() {
            return Err("Tokio worker observer is already installed".to_owned());
        }
        if !matches!(context.flavor, Flavor::MultiThread) {
            drop(callback);
            return Ok(());
        }
        let callback = Arc::new(WorkerCallbackOwner(callback));
        let owner = Arc::clone(&context.owner);
        let id = context
            .handle
            .telekio_add_worker_observer(Arc::new(move |worker| {
                let Some(_activity) = owner.callback(std::task::Waker::noop().clone()) else {
                    return;
                };
                callback
                    .call(worker)
                    .resume("failed to record Tokio worker thread");
            }));
        *observer = Some(WorkerObserver {
            handle: context.handle.clone(),
            id,
        });
        Ok(())
    })) {
        Ok(Ok(())) => CallResult::ok(),
        Ok(Err(error)) => result(Status::Error, OwnedBytes::from_string(error)),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn block_in_place(context: *const c_void, blocking: Blocking) -> CallResult {
    let outcome = catch_unwind(AssertUnwindSafe(|| -> Result<Status, String> {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let activity = context.owner.activity()?;
        context.owner.wake_activities();
        let status = tokio::task::block_in_place(|| unsafe { blocking.run() });
        drop(activity);
        Ok(status)
    }));
    match outcome {
        Ok(Ok(status)) => result(status, OwnedBytes::empty()),
        Ok(Err(error)) => result(Status::Error, OwnedBytes::from_string(error)),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn build(context: *const c_void, config: RuntimeConfig) -> BuildResult {
    match catch_unwind(AssertUnwindSafe(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let _activity = match context.owner.activity() {
            Ok(activity) => activity,
            Err(error) => {
                return BuildResult::error(result(Status::Error, OwnedBytes::from_string(error)));
            }
        };
        match build_runtime(config, Arc::clone(&context.owner)) {
            Ok((kind, handle, workers)) => {
                let runtime = Arc::new(RuntimeOwner {
                    id: OnceLock::new(),
                    owner: Arc::downgrade(&context.owner),
                    kind: RwLock::new(kind),
                });
                let id = match context.owner.register_runtime(Arc::clone(&runtime)) {
                    Ok(id) => id,
                    Err(error) => {
                        let closed = std::thread::spawn(move || {
                            runtime.close(Shutdown::Wait, Duration::ZERO)
                        })
                        .join();
                        return BuildResult::error(match closed {
                            Ok(Ok(())) => result(Status::Error, OwnedBytes::from_string(error)),
                            Ok(Err(error)) => {
                                result(Status::Error, OwnedBytes::from_string(error.to_string()))
                            }
                            Err(payload) => host_panic(&*payload),
                        });
                    }
                };
                runtime.id.set(id).unwrap();
                let raw_handle = raw_handle(handle);
                BuildResult::success(
                    unsafe {
                        RawRuntime::from_raw(Arc::as_ptr(&runtime).cast_mut().cast(), raw_handle)
                    },
                    workers,
                )
            }
            Err(error) => BuildResult::error(result(
                Status::Error,
                OwnedBytes::from_string(error.to_string()),
            )),
        }
    })) {
        Ok(result) => result,
        Err(payload) => BuildResult::error(host_panic(&*payload)),
    }
}

unsafe extern "C" fn clock(context: *const c_void) -> telekio::ClockResult {
    match catch_unwind(AssertUnwindSafe(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let origin = *CLOCK_ORIGIN.get_or_init(std::time::Instant::now);
        let realtime = instant_offset(origin, std::time::Instant::now());
        let _guard = context.handle.enter();
        let logical = instant_offset(origin, tokio::time::Instant::now().into_std());
        ClockSample { realtime, logical }
    })) {
        Ok(value) => telekio::ClockResult {
            call: CallResult::ok(),
            value,
        },
        Err(payload) => telekio::ClockResult {
            call: host_panic(&*payload),
            value: ClockSample {
                realtime: InstantOffset {
                    duration: DurationParts::new(Duration::ZERO),
                    negative: 0,
                },
                logical: InstantOffset {
                    duration: DurationParts::new(Duration::ZERO),
                    negative: 0,
                },
            },
        },
    }
}

unsafe extern "C" fn pause(context: *const c_void) -> CallResult {
    time_call(context, tokio::time::pause)
}

unsafe extern "C" fn resume(context: *const c_void) -> CallResult {
    time_call(context, tokio::time::resume)
}

fn time_call(context: *const c_void, call: impl FnOnce()) -> CallResult {
    let context = unsafe { &*context.cast::<HandleContext>() };
    match catch_unwind(AssertUnwindSafe(|| {
        let _guard = context.handle.enter();
        call();
    })) {
        Ok(()) => result(Status::Ok, OwnedBytes::empty()),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn advance(context: *const c_void, duration: DurationParts) -> CallResult {
    let context = unsafe { &*context.cast::<HandleContext>() };
    match catch_unwind(AssertUnwindSafe(|| {
        let _guard = context.handle.enter();
        let mut operation = std::pin::pin!(tokio::time::advance(duration.duration()));
        let mut context = TaskContext::from_waker(std::task::Waker::noop());
        _ = operation.as_mut().poll(&mut context);
    })) {
        Ok(()) => result(Status::Ok, OwnedBytes::empty()),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn timer(context: *const c_void, deadline: InstantOffset) -> TimerResult {
    let context = unsafe { &*context.cast::<HandleContext>() };
    match catch_unwind(AssertUnwindSafe(|| {
        let _guard = context.handle.enter();
        HostResource::new(
            &context.owner,
            TimeTimer {
                sleep: Box::pin(tokio::time::sleep_until(time_instant(deadline))),
            },
        )
    })) {
        Ok(Ok(timer)) => TimerResult {
            call: result(Status::Ok, OwnedBytes::empty()),
            timer: unsafe {
                Timer::from_raw(
                    Arc::as_ptr(&timer).cast_mut().cast(),
                    poll_time_timer,
                    reset_time_timer,
                    time_timer_elapsed,
                    release_time_timer,
                )
            },
        },
        Ok(Err(error)) => TimerResult {
            call: result(Status::Error, OwnedBytes::from_string(error)),
            timer: Timer::empty(),
        },
        Err(payload) => TimerResult {
            call: host_panic(&*payload),
            timer: Timer::empty(),
        },
    }
}

unsafe extern "C" fn poll_time_timer(data: *mut c_void, waker: *const Waker) -> OperationPoll {
    match catch_unwind(AssertUnwindSafe(|| {
        let timer = unsafe { &*data.cast::<HostResource<TimeTimer>>() };
        timer.update_waker(unsafe { &*waker });
        let waker = unsafe { (*waker).clone_rust_waker() };
        let mut context = TaskContext::from_waker(&waker);
        timer.with_mut(|timer| timer.sleep.as_mut().poll(&mut context))
    })) {
        Ok(Ok(RustPoll::Pending)) => {
            time_poll(Poll::Pending, result(Status::Ok, OwnedBytes::empty()))
        }
        Ok(Ok(RustPoll::Ready(()))) => {
            time_poll(Poll::Ready, result(Status::Ok, OwnedBytes::empty()))
        }
        Ok(Err(error)) => time_poll(
            Poll::Ready,
            result(Status::Error, OwnedBytes::from_string(error)),
        ),
        Err(payload) => time_poll(Poll::Panicked, host_panic(&*payload)),
    }
}

unsafe extern "C" fn reset_time_timer(data: *mut c_void, deadline: InstantOffset) -> CallResult {
    let timer = unsafe { &*data.cast::<HostResource<TimeTimer>>() };
    match catch_unwind(AssertUnwindSafe(|| {
        timer.with_mut(|timer| {
            timer.sleep.as_mut().reset(time_instant(deadline));
        })
    })) {
        Ok(Ok(())) => result(Status::Ok, OwnedBytes::empty()),
        Ok(Err(error)) => result(Status::Error, OwnedBytes::from_string(error)),
        Err(payload) => host_panic(&*payload),
    }
}

unsafe extern "C" fn time_timer_elapsed(data: *const c_void) -> telekio::BoolResult {
    match catch_unwind(AssertUnwindSafe(|| {
        unsafe { &*data.cast::<HostResource<TimeTimer>>() }
            .with(|timer| timer.sleep.is_elapsed())
            .unwrap_or(true)
    })) {
        Ok(value) => telekio::BoolResult {
            call: CallResult::ok(),
            value,
        },
        Err(payload) => telekio::BoolResult {
            call: host_panic(&*payload),
            value: true,
        },
    }
}

unsafe extern "C" fn release_time_timer(data: *mut c_void) -> CallResult {
    host_callback(|| unsafe { &*data.cast::<HostResource<TimeTimer>>() }.release())
}

fn time_instant(offset: InstantOffset) -> tokio::time::Instant {
    let origin = *CLOCK_ORIGIN.get_or_init(std::time::Instant::now);
    tokio::time::Instant::from_std(offset.apply(origin))
}

fn time_poll(state: Poll, call: CallResult) -> OperationPoll {
    OperationPoll { state, call }
}

fn instant_offset(origin: std::time::Instant, instant: std::time::Instant) -> InstantOffset {
    match instant.checked_duration_since(origin) {
        Some(duration) => InstantOffset {
            duration: DurationParts::new(duration),
            negative: 0,
        },
        None => InstantOffset {
            duration: DurationParts::new(origin.duration_since(instant)),
            negative: 1,
        },
    }
}

unsafe extern "C" fn reap_process(context: *const c_void, id: u32) -> CallResult {
    #[cfg(unix)]
    {
        match catch_unwind(AssertUnwindSafe(|| {
            let context = unsafe { &*context.cast::<HandleContext>() };
            let _guard = context.handle.enter();
            let signal = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::child());
            match signal {
                Ok(mut signal) => {
                    context.handle.spawn(async move {
                        loop {
                            let result = unsafe {
                                libc::waitpid(
                                    id as libc::pid_t,
                                    std::ptr::null_mut(),
                                    libc::WNOHANG,
                                )
                            };
                            if result > 0 {
                                break;
                            }
                            if result < 0 {
                                if io::Error::last_os_error().kind() == io::ErrorKind::Interrupted {
                                    continue;
                                }
                                break;
                            }
                            signal.recv().await;
                        }
                    });
                    result(Status::Ok, OwnedBytes::empty())
                }
                Err(error) => result(Status::Error, OwnedBytes::from_string(error.to_string())),
            }
        })) {
            Ok(result) => result,
            Err(payload) => host_panic(&*payload),
        }
    }
    #[cfg(not(unix))]
    {
        let _ = (context, id);
        result(Status::Ok, OwnedBytes::empty())
    }
}

unsafe extern "C" fn shutdown(
    owner: *mut c_void,
    mode: Shutdown,
    seconds: u64,
    nanoseconds: u32,
) -> CallResult {
    let runtime = unsafe { &*owner.cast::<RuntimeOwner>() };
    match catch_unwind(AssertUnwindSafe(|| {
        runtime
            .close(mode, Duration::new(seconds, nanoseconds))
            .unwrap_or_else(|error| panic!("{error}"));
    })) {
        Ok(()) => result(Status::Ok, OwnedBytes::empty()),
        Err(payload) => host_panic(&*payload),
    }
}

fn build_runtime(
    config: RuntimeConfig,
    owner: Arc<OwnerState>,
) -> io::Result<(RuntimeKind, Arc<HandleContext>, usize)> {
    let thread_name = Arc::new(StringCallbackOwner(config.thread_name));
    let after_start = Arc::new(CallbackOwner(config.after_start));
    let before_stop = Arc::new(CallbackOwner(config.before_stop));
    let before_park = Arc::new(CallbackOwner(config.before_park));
    let after_unpark = Arc::new(CallbackOwner(config.after_unpark));
    let mut builder = match config.flavor {
        Flavor::CurrentThread | Flavor::Local => tokio::runtime::Builder::new_current_thread(),
        Flavor::MultiThread => tokio::runtime::Builder::new_multi_thread(),
    };

    if config.enable_io != 0 {
        builder.enable_io();
    }
    if config.enable_time != 0 {
        builder.enable_time();
    }
    if config.start_paused != 0 {
        builder.start_paused(true);
    }
    if config.worker_threads != 0 {
        builder.worker_threads(config.worker_threads);
    }
    builder.max_blocking_threads(config.max_blocking_threads);
    if config.has_thread_stack_size != 0 {
        builder.thread_stack_size(config.thread_stack_size);
    }
    if config.has_keep_alive != 0 {
        builder.thread_keep_alive(Duration::new(
            config.keep_alive_secs,
            config.keep_alive_nanos,
        ));
    }
    if config.global_queue_interval != 0 {
        builder.global_queue_interval(config.global_queue_interval);
    }
    builder.event_interval(config.event_interval);
    builder.max_io_events_per_tick(config.max_io_events_per_tick);
    if config.disable_lifo_slot != 0 {
        builder.telekio_disable_lifo_slot();
    }
    if config.eager_driver_handoff != 0 {
        builder.telekio_enable_eager_driver_handoff();
    }
    if config.alternative_timer != 0 {
        builder.telekio_enable_alt_timer();
    }
    builder.telekio_poll_histogram(
        config.poll_histogram.kind,
        config.poll_histogram.a,
        config.poll_histogram.b,
        config.poll_histogram.c,
    );
    builder.telekio_schedule_histogram(
        config.schedule_histogram.kind,
        config.schedule_histogram.a,
        config.schedule_histogram.b,
        config.schedule_histogram.c,
    );
    if !config.name.is_empty() {
        builder.name(unsafe { config.name.as_str() });
    }

    builder.thread_name_fn(move || thread_name.call());
    if after_start.is_some() {
        builder.on_thread_start(move || after_start.call());
    }
    if before_stop.is_some() {
        builder.on_thread_stop(move || before_stop.call());
    }
    if before_park.is_some() {
        builder.on_thread_park(move || before_park.call());
    }
    if after_unpark.is_some() {
        builder.on_thread_unpark(move || after_unpark.call());
    }

    match config.flavor {
        Flavor::CurrentThread | Flavor::MultiThread => {
            let runtime = builder.build()?;
            let workers = runtime.handle().metrics().num_workers();
            let handle = handle_context(
                runtime.handle().clone(),
                Arc::clone(&owner),
                None,
                config.enable_io != 0,
                config.flavor,
            );
            Ok((RuntimeKind::Runtime(Some(runtime)), handle, workers))
        }
        Flavor::Local => {
            let runtime = builder.build_local(Default::default())?;
            let handle = runtime.handle().clone();
            let workers = handle.metrics().num_workers();
            let local = Arc::new(LocalSlot::new(runtime));
            let handle = handle_context(
                handle,
                owner,
                Some(Arc::clone(&local)),
                config.enable_io != 0,
                config.flavor,
            );
            Ok((RuntimeKind::Local(local), handle, workers))
        }
    }
}

fn handle_context(
    handle: tokio::runtime::Handle,
    owner: Arc<OwnerState>,
    local: Option<Arc<LocalSlot>>,
    io_enabled: bool,
    flavor: Flavor,
) -> Arc<HandleContext> {
    Arc::new(HandleContext {
        handle,
        owner,
        local,
        io_enabled,
        flavor,
        worker_observer: Mutex::new(None),
    })
}

fn raw_handle(context: Arc<HandleContext>) -> RawHandle {
    context.owner.export_handle(Arc::clone(&context));
    unsafe { RawHandle::from_raw(Arc::as_ptr(&context).cast(), &raw const RUNTIME_API) }
}

fn shutdown_runtime(runtime: tokio::runtime::Runtime, mode: Shutdown, duration: Duration) {
    match mode {
        Shutdown::Wait => drop(runtime),
        Shutdown::Background => runtime.shutdown_background(),
        Shutdown::Timeout => runtime.shutdown_timeout(duration),
    }
}

fn shutdown_local(runtime: tokio::runtime::LocalRuntime, mode: Shutdown, duration: Duration) {
    match mode {
        Shutdown::Wait => drop(runtime),
        Shutdown::Background => runtime.shutdown_background(),
        Shutdown::Timeout => runtime.shutdown_timeout(duration),
    }
}

fn result(status: Status, payload: OwnedBytes) -> CallResult {
    CallResult { status, payload }
}

fn host_panic(payload: &(dyn Any + Send)) -> CallResult {
    result(
        Status::HostPanicked,
        OwnedBytes::from_string(panic_message(payload)),
    )
}

pub(crate) fn host_callback(call: impl FnOnce()) -> CallResult {
    match catch_unwind(AssertUnwindSafe(call)) {
        Ok(()) => CallResult::ok(),
        Err(payload) => host_panic(&*payload),
    }
}

fn panic_message(payload: &(dyn Any + Send)) -> String {
    payload
        .downcast_ref::<String>()
        .cloned()
        .or_else(|| {
            payload
                .downcast_ref::<&'static str>()
                .map(|message| (*message).to_owned())
        })
        .unwrap_or_else(|| "Box<dyn Any>".to_owned())
}
