use std::{
    cell::Cell,
    collections::HashMap,
    ffi::c_void,
    fmt, io,
    panic::{AssertUnwindSafe, catch_unwind},
    sync::{Arc, Mutex, OnceLock},
    time::Duration,
};

use telekio_abi::{
    AttachResult, CallResult, GuestCall, OwnedBytes, RawAttachment, RawHandle, Shutdown, Status,
    Waker,
};

use super::runtime::{HandleContext, RuntimeOwner, raw_handle};
use super::{host_callback, host_panic, result};

/// A runtime's task and resource ownership for one plugin.
pub struct Owner {
    pub(super) runtime: Arc<crate::runtime::Runtime>,
    pub(super) handle: Arc<HandleContext>,
}

/// Plugin entry generated by `telekio_abi::plugin!()`.
pub type Attach = unsafe extern "C" fn(RawHandle) -> AttachResult;

/// One loaded plugin's connection to a Telekio owner.
#[must_use = "the attachment must be shut down before unloading its plugin"]
pub struct Attachment {
    raw: Option<RawAttachment>,
    owner: Arc<OwnerState>,
}

struct GuestCallState<F, R> {
    call: Option<F>,
    output: Option<R>,
}

pub(super) struct OwnerState {
    state: Mutex<OwnerStatus>,
    notify: crate::sync::Notify,
    shutdown: crate::sync::Mutex<()>,
}

struct OwnerStatus {
    accepting: bool,
    handles: HashMap<usize, HandleRecord>,
    tasks: HashMap<u64, TaskRecord>,
    activities: HashMap<u64, Option<std::task::Waker>>,
    runtimes: HashMap<u64, Arc<RuntimeOwner>>,
    resources: HashMap<u64, Arc<dyn OwnerResource>>,
    next_id: u64,
}

struct HandleRecord {
    context: Arc<HandleContext>,
    references: usize,
}

struct TaskRecord {
    handle: Option<crate::task::AbortHandle>,
}

trait OwnerResource: Send + Sync {
    fn close(&self);
    fn is_closed(&self) -> bool;
}

pub(super) struct HostResource<T: Send> {
    pub(super) owner: Arc<OwnerState>,
    id: OnceLock<u64>,
    value: Mutex<Option<T>>,
    waker: Mutex<Option<std::task::Waker>>,
}

pub(super) struct Activity {
    pub(super) owner: Arc<OwnerState>,
    pub(super) id: u64,
    _context: OwnerContext,
}

pub(super) struct OwnerContext {
    previous: *const OwnerState,
}

pub(super) struct TaskCleanup {
    pub(super) owner: Arc<OwnerState>,
    pub(super) id: u64,
}

pub(super) struct CallbackCleanup {
    owner: Arc<OwnerState>,
    id: u64,
}

thread_local! {
    static ACTIVE_OWNER: Cell<*const OwnerState> = const { Cell::new(std::ptr::null()) };
}

impl fmt::Debug for Owner {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("Owner")
            .field("runtime", &self.runtime)
            .finish_non_exhaustive()
    }
}

impl fmt::Debug for Attachment {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("Attachment")
            .field("attached", &self.raw.is_some())
            .finish_non_exhaustive()
    }
}

impl Owner {
    /// Returns the ABI handle for this owner's runtime services.
    pub fn runtime(&self) -> telekio_abi::Handle {
        unsafe { telekio_abi::Handle::from_abi(raw_handle(Arc::clone(&self.handle))) }
    }

    /// Stops this owner's work and waits for its active calls.
    pub async fn shutdown(&self) -> io::Result<()> {
        if ACTIVE_OWNER.get() == Arc::as_ptr(&self.handle.owner) {
            return Err(io::Error::other(
                "owner shutdown cannot run inside one of its guest callbacks",
            ));
        }
        let _shutdown = self.handle.owner.shutdown.lock().await;
        shutdown_owner(&self.handle.owner, self.runtime.handle()).await
    }

    /// # Safety
    ///
    /// `attach` must belong to a loaded plugin and remain callable until this
    /// owner's attachment is detached.
    pub unsafe fn attach(&self, attach: Attach) -> io::Result<Attachment> {
        let result = unsafe { attach(self.runtime().into_abi()) };
        result.call.into_io_result()?;
        Ok(Attachment {
            raw: Some(result.attachment),
            owner: Arc::clone(&self.handle.owner),
        })
    }

    /// Stops this owner and detaches its plugin before the library is unloaded.
    pub async fn detach(&self, attachment: &mut Attachment) -> io::Result<()> {
        if !Arc::ptr_eq(&self.handle.owner, &attachment.owner) {
            return Err(io::Error::other(
                "Telekio attachment belongs to another owner",
            ));
        }
        self.shutdown().await?;
        attachment.detach()
    }
}

impl Attachment {
    /// Runs a plugin entry inside its attached Tokio runtime context.
    pub fn enter<F: FnOnce() -> R, R>(&self, call: F) -> R {
        let raw = self.raw.as_ref().expect("Telekio attachment is detached");
        let activity = self
            .owner
            .activity()
            .unwrap_or_else(|error| panic!("{error}"));
        let mut state = GuestCallState {
            call: Some(call),
            output: None,
        };
        let call = unsafe { GuestCall::from_raw((&raw mut state).cast(), run_guest_call::<F, R>) };
        crate::runtime::telekio::with_execution(|state| unsafe { raw.enter(state.cast(), call) })
            .resume("failed to enter Telekio guest runtime");
        drop(activity);
        state.output.take().expect("Telekio guest call did not run")
    }

    fn detach(&mut self) -> io::Result<()> {
        let raw = self
            .raw
            .as_ref()
            .ok_or_else(|| io::Error::other("Telekio attachment is already detached"))?;
        unsafe { raw.detach() }.into_io_result()?;
        self.raw = None;
        Ok(())
    }
}

unsafe extern "C" fn run_guest_call<F: FnOnce() -> R, R>(data: *mut c_void) -> CallResult {
    let state = unsafe { &mut *data.cast::<GuestCallState<F, R>>() };
    match catch_unwind(AssertUnwindSafe(|| {
        let call = state.call.take().expect("Telekio guest call ran twice");
        state.output = Some(call());
    })) {
        Ok(()) => CallResult::ok(),
        Err(payload) => CallResult::panicked(&*payload),
    }
}

pub(super) fn owner_state() -> Arc<OwnerState> {
    Arc::new(OwnerState {
        state: Mutex::new(OwnerStatus {
            accepting: true,
            handles: HashMap::new(),
            tasks: HashMap::new(),
            activities: HashMap::new(),
            runtimes: HashMap::new(),
            resources: HashMap::new(),
            next_id: 1,
        }),
        notify: crate::sync::Notify::const_new(),
        shutdown: crate::sync::Mutex::const_new(()),
    })
}

impl OwnerState {
    pub(super) fn is_accepting(&self) -> bool {
        self.state.lock().unwrap().accepting
    }

    pub(super) fn callback(self: &Arc<Self>, waker: std::task::Waker) -> Option<CallbackCleanup> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return None;
        }
        let id = state.next_id;
        state.next_id += 1;
        state.activities.insert(id, Some(waker));
        Some(CallbackCleanup {
            owner: Arc::clone(self),
            id,
        })
    }

    pub(super) fn activity(self: &Arc<Self>) -> Result<Activity, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.activities.insert(id, None);
        Ok(Activity {
            owner: Arc::clone(self),
            id,
            _context: OwnerContext::enter(self),
        })
    }

    pub(super) fn update_activity_waker(&self, id: u64, waker: &std::task::Waker) -> bool {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return false;
        }
        if let Some(slot) = state.activities.get_mut(&id) {
            *slot = Some(waker.clone());
        }
        true
    }

    #[cfg(feature = "rt-multi-thread")]
    pub(super) fn wake_activities(&self) {
        let wakers = self
            .state
            .lock()
            .unwrap()
            .activities
            .values()
            .filter_map(Clone::clone)
            .collect::<Vec<_>>();
        for waker in wakers {
            waker.wake();
        }
    }

    pub(super) fn export_handle(&self, context: Arc<HandleContext>) {
        let key = Arc::as_ptr(&context) as usize;
        let mut state = self.state.lock().unwrap();
        let handle = state.handles.entry(key).or_insert(HandleRecord {
            context,
            references: 0,
        });
        handle.references += 1;
    }

    fn retain_handle(&self, context: *const HandleContext) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        let handle = state
            .handles
            .get_mut(&(context as usize))
            .ok_or_else(|| "Tokio handle is detached".to_owned())?;
        handle.references += 1;
        Ok(())
    }

    fn release_handle(&self, context: *const HandleContext) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        let key = context as usize;
        let handle = state
            .handles
            .get_mut(&key)
            .ok_or_else(|| "Tokio handle is detached".to_owned())?;
        handle.references = handle
            .references
            .checked_sub(1)
            .ok_or_else(|| "Tokio handle reference count is empty".to_owned())?;
        let _handle = if handle.references == 0 {
            state.handles.remove(&key)
        } else {
            None
        };
        Ok(())
    }

    pub(super) fn reserve_task(&self, id: u64) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        match state.tasks.entry(id) {
            std::collections::hash_map::Entry::Vacant(task) => {
                task.insert(TaskRecord { handle: None });
                Ok(())
            }
            std::collections::hash_map::Entry::Occupied(_) => {
                Err(format!("Tokio task {id} is already registered"))
            }
        }
    }

    pub(super) fn register_task(&self, id: u64, handle: crate::task::AbortHandle) {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            handle.abort();
        }
        if let Some(task) = state.tasks.get_mut(&id) {
            task.handle = Some(handle);
        }
    }

    pub(super) fn abort_task(&self, id: u64) {
        let handle = self
            .state
            .lock()
            .unwrap()
            .tasks
            .get(&id)
            .and_then(|task| task.handle.clone());
        if let Some(handle) = handle {
            handle.abort();
        }
    }

    pub(super) fn finish_task(&self, id: u64) {
        self.state.lock().unwrap().tasks.remove(&id);
        self.notify.notify_waiters();
    }

    pub(super) fn register_runtime(&self, runtime: Arc<RuntimeOwner>) -> Result<u64, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.runtimes.insert(id, runtime);
        Ok(id)
    }

    pub(super) fn unregister_runtime(&self, id: u64) -> Option<Arc<RuntimeOwner>> {
        self.state.lock().unwrap().runtimes.remove(&id)
    }

    fn register_resource(&self, resource: Arc<dyn OwnerResource>) -> Result<u64, String> {
        let mut state = self.state.lock().unwrap();
        if !state.accepting {
            return Err("Tokio owner is shutting down".to_owned());
        }
        let id = state.next_id;
        state.next_id += 1;
        state.resources.insert(id, resource);
        Ok(id)
    }

    fn unregister_resource(&self, id: u64) -> Option<Arc<dyn OwnerResource>> {
        self.state.lock().unwrap().resources.remove(&id)
    }

    fn begin_shutdown(
        &self,
    ) -> (
        Vec<crate::task::AbortHandle>,
        Vec<Arc<dyn OwnerResource>>,
        Vec<std::task::Waker>,
    ) {
        let mut state = self.state.lock().unwrap();
        state.accepting = false;
        let tasks = state
            .tasks
            .values()
            .filter_map(|task| task.handle.clone())
            .collect();
        let resources = state.resources.values().cloned().collect();
        let activities = state.activities.values().filter_map(Clone::clone).collect();
        (tasks, resources, activities)
    }

    async fn wait_idle(&self) {
        loop {
            let notified = self.notify.notified();
            let idle = {
                let state = self.state.lock().unwrap();
                state.tasks.is_empty() && state.activities.is_empty()
            };
            if idle {
                return;
            }
            notified.await;
        }
    }

    fn runtimes(&self) -> io::Result<Vec<Arc<RuntimeOwner>>> {
        let state = self.state.lock().unwrap();
        if state.runtimes.values().any(|runtime| runtime.local_open()) {
            return Err(io::Error::other(
                "LocalRuntime must be dropped on its originating thread before owner shutdown",
            ));
        }
        Ok(state.runtimes.values().cloned().collect())
    }

    fn detach(&self) -> Result<(), String> {
        let mut state = self.state.lock().unwrap();
        if state.accepting || !state.tasks.is_empty() || !state.activities.is_empty() {
            return Err("Tokio owner must shut down before detaching".to_owned());
        }
        if state.runtimes.values().any(|runtime| !runtime.is_closed())
            || state
                .resources
                .values()
                .any(|resource| !resource.is_closed())
        {
            return Err("Tokio owner has live runtime resources".to_owned());
        }
        debug_assert!(
            state
                .handles
                .iter()
                .all(|(key, handle)| *key == Arc::as_ptr(&handle.context) as usize)
        );
        state.handles.clear();
        state.runtimes.clear();
        state.resources.clear();
        Ok(())
    }
}

impl OwnerContext {
    pub(super) fn enter(owner: &Arc<OwnerState>) -> Self {
        Self {
            previous: ACTIVE_OWNER.replace(Arc::as_ptr(owner)),
        }
    }
}

impl Drop for OwnerContext {
    fn drop(&mut self) {
        ACTIVE_OWNER.set(self.previous);
    }
}

impl Drop for Activity {
    fn drop(&mut self) {
        self.owner.state.lock().unwrap().activities.remove(&self.id);
        self.owner.notify.notify_waiters();
    }
}

impl Drop for TaskCleanup {
    fn drop(&mut self) {
        self.owner.finish_task(self.id);
    }
}

impl Drop for CallbackCleanup {
    fn drop(&mut self) {
        self.owner.state.lock().unwrap().activities.remove(&self.id);
        self.owner.notify.notify_waiters();
    }
}

impl<T: Send + 'static> OwnerResource for HostResource<T> {
    fn close(&self) {
        self.value.lock().unwrap().take();
        if let Some(waker) = self.waker.lock().unwrap().take() {
            waker.wake();
        }
    }

    fn is_closed(&self) -> bool {
        self.value.lock().unwrap().is_none()
    }
}

impl<T: Send + 'static> HostResource<T> {
    pub(super) fn new(owner: &Arc<OwnerState>, value: T) -> Result<Arc<Self>, String> {
        let resource = Arc::new(Self {
            owner: Arc::clone(owner),
            id: OnceLock::new(),
            value: Mutex::new(Some(value)),
            waker: Mutex::new(None),
        });
        let id = owner.register_resource(Arc::clone(&resource) as Arc<dyn OwnerResource>)?;
        resource.id.set(id).unwrap();
        Ok(resource)
    }

    pub(super) fn update_waker(&self, waker: &Waker) {
        let value = self.value.lock().unwrap();
        if value.is_some() {
            *self.waker.lock().unwrap() = Some(unsafe { waker.clone_rust_waker() });
        }
    }

    #[cfg(any(
        feature = "time",
        feature = "net",
        all(unix, any(feature = "process", feature = "signal")),
        all(
            tokio_unstable,
            target_os = "linux",
            feature = "fs",
            feature = "io-uring"
        )
    ))]
    pub(super) fn with<R>(&self, call: impl FnOnce(&T) -> R) -> Result<R, String> {
        self.value
            .lock()
            .unwrap()
            .as_ref()
            .map(call)
            .ok_or_else(|| "Tokio owner has shut down".to_owned())
    }

    pub(super) fn with_mut<R>(&self, call: impl FnOnce(&mut T) -> R) -> Result<R, String> {
        self.value
            .lock()
            .unwrap()
            .as_mut()
            .map(call)
            .ok_or_else(|| "Tokio owner has shut down".to_owned())
    }

    pub(super) fn release(&self) {
        let _resource = self.owner.unregister_resource(*self.id.get().unwrap());
    }
}

async fn shutdown_owner(
    owner: &Arc<OwnerState>,
    handle: &crate::runtime::Handle,
) -> io::Result<()> {
    let (tasks, resources, activities) = owner.begin_shutdown();
    for task in tasks {
        task.abort();
    }
    for resource in resources {
        resource.close();
    }
    for activity in activities {
        activity.wake();
    }

    let runtimes = owner.runtimes()?;
    let close = handle.spawn_blocking(move || {
        for runtime in runtimes {
            runtime.close(Shutdown::Wait, Duration::ZERO)?;
        }
        Ok::<_, io::Error>(())
    });
    close.await.map_err(io::Error::other)??;
    owner.wait_idle().await;
    Ok(())
}

pub(super) unsafe extern "C" fn retain_handle(context: *const c_void) -> CallResult {
    host_callback(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let owner = Arc::clone(&context.owner);
        owner
            .retain_handle(context)
            .unwrap_or_else(|error| panic!("{error}"));
    })
}

pub(super) unsafe extern "C" fn release_handle(context: *const c_void) -> CallResult {
    host_callback(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        let owner = Arc::clone(&context.owner);
        owner
            .release_handle(context)
            .unwrap_or_else(|error| panic!("{error}"));
    })
}

pub(super) unsafe extern "C" fn detach(context: *const c_void) -> CallResult {
    match catch_unwind(AssertUnwindSafe(|| {
        let context = unsafe { &*context.cast::<HandleContext>() };
        Arc::clone(&context.owner).detach()
    })) {
        Ok(Ok(())) => CallResult::ok(),
        Ok(Err(error)) => result(Status::Error, OwnedBytes::from_string(error)),
        Err(payload) => host_panic(&*payload),
    }
}
